# Generated from metalstack/api/v2/audit.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.11.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync

from .audit_pb import AuditServiceGetRequest, AuditServiceGetResponse, AuditServiceListRequest, AuditServiceListResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext


class AuditService(Protocol):
    async def get(self, request: AuditServiceGetRequest, ctx: RequestContext[AuditServiceGetRequest, AuditServiceGetResponse]) -> AuditServiceGetResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list(self, request: AuditServiceListRequest, ctx: RequestContext[AuditServiceListRequest, AuditServiceListResponse]) -> AuditServiceListResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class AuditServiceASGIApplication(ConnectASGIApplication[AuditService]):
    def __init__(
        self,
        service: AuditService | AsyncGenerator[AuditService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/metalstack.api.v2.AuditService/Get": Endpoint.unary(
                    method=MethodInfo(
                        name="Get",
                        service_name="metalstack.api.v2.AuditService",
                        input=AuditServiceGetRequest,
                        output=AuditServiceGetResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get,
                ),
                "/metalstack.api.v2.AuditService/List": Endpoint.unary(
                    method=MethodInfo(
                        name="List",
                        service_name="metalstack.api.v2.AuditService",
                        input=AuditServiceListRequest,
                        output=AuditServiceListResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/metalstack.api.v2.AuditService"


class AuditServiceClient(ConnectClient):
    async def get(
        self,
        request: AuditServiceGetRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> AuditServiceGetResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Get",
                service_name="metalstack.api.v2.AuditService",
                input=AuditServiceGetRequest,
                output=AuditServiceGetResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list(
        self,
        request: AuditServiceListRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> AuditServiceListResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="List",
                service_name="metalstack.api.v2.AuditService",
                input=AuditServiceListRequest,
                output=AuditServiceListResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class AuditServiceSync(Protocol):
    def get(self, request: AuditServiceGetRequest, ctx: RequestContext[AuditServiceGetRequest, AuditServiceGetResponse]) -> AuditServiceGetResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list(self, request: AuditServiceListRequest, ctx: RequestContext[AuditServiceListRequest, AuditServiceListResponse]) -> AuditServiceListResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class AuditServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: AuditServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/metalstack.api.v2.AuditService/Get": EndpointSync.unary(
                    method=MethodInfo(
                        name="Get",
                        service_name="metalstack.api.v2.AuditService",
                        input=AuditServiceGetRequest,
                        output=AuditServiceGetResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get,
                ),
                "/metalstack.api.v2.AuditService/List": EndpointSync.unary(
                    method=MethodInfo(
                        name="List",
                        service_name="metalstack.api.v2.AuditService",
                        input=AuditServiceListRequest,
                        output=AuditServiceListResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/metalstack.api.v2.AuditService"


class AuditServiceClientSync(ConnectClientSync):
    def get(
        self,
        request: AuditServiceGetRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> AuditServiceGetResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Get",
                service_name="metalstack.api.v2.AuditService",
                input=AuditServiceGetRequest,
                output=AuditServiceGetResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list(
        self,
        request: AuditServiceListRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> AuditServiceListResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="List",
                service_name="metalstack.api.v2.AuditService",
                input=AuditServiceListRequest,
                output=AuditServiceListResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
