# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: metalstack/api/v2/audit.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import metalstack.api.v2.audit_pb2 as metalstack_dot_api_dot_v2_dot_audit__pb2


class AuditService(Protocol):
    async def get(self, request: metalstack_dot_api_dot_v2_dot_audit__pb2.AuditServiceGetRequest, ctx: RequestContext) -> metalstack_dot_api_dot_v2_dot_audit__pb2.AuditServiceGetResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list(self, request: metalstack_dot_api_dot_v2_dot_audit__pb2.AuditServiceListRequest, ctx: RequestContext) -> metalstack_dot_api_dot_v2_dot_audit__pb2.AuditServiceListResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class AuditServiceASGIApplication(ConnectASGIApplication[AuditService]):
    def __init__(self, service: AuditService | AsyncGenerator[AuditService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/metalstack.api.v2.AuditService/Get": Endpoint.unary(
                    method=MethodInfo(
                        name="Get",
                        service_name="metalstack.api.v2.AuditService",
                        input=metalstack_dot_api_dot_v2_dot_audit__pb2.AuditServiceGetRequest,
                        output=metalstack_dot_api_dot_v2_dot_audit__pb2.AuditServiceGetResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get,
                ),
                "/metalstack.api.v2.AuditService/List": Endpoint.unary(
                    method=MethodInfo(
                        name="List",
                        service_name="metalstack.api.v2.AuditService",
                        input=metalstack_dot_api_dot_v2_dot_audit__pb2.AuditServiceListRequest,
                        output=metalstack_dot_api_dot_v2_dot_audit__pb2.AuditServiceListResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/metalstack.api.v2.AuditService"


class AuditServiceClient(ConnectClient):
    async def get(
        self,
        request: metalstack_dot_api_dot_v2_dot_audit__pb2.AuditServiceGetRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> metalstack_dot_api_dot_v2_dot_audit__pb2.AuditServiceGetResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Get",
                service_name="metalstack.api.v2.AuditService",
                input=metalstack_dot_api_dot_v2_dot_audit__pb2.AuditServiceGetRequest,
                output=metalstack_dot_api_dot_v2_dot_audit__pb2.AuditServiceGetResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list(
        self,
        request: metalstack_dot_api_dot_v2_dot_audit__pb2.AuditServiceListRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> metalstack_dot_api_dot_v2_dot_audit__pb2.AuditServiceListResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="List",
                service_name="metalstack.api.v2.AuditService",
                input=metalstack_dot_api_dot_v2_dot_audit__pb2.AuditServiceListRequest,
                output=metalstack_dot_api_dot_v2_dot_audit__pb2.AuditServiceListResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class AuditServiceSync(Protocol):
    def get(self, request: metalstack_dot_api_dot_v2_dot_audit__pb2.AuditServiceGetRequest, ctx: RequestContext) -> metalstack_dot_api_dot_v2_dot_audit__pb2.AuditServiceGetResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list(self, request: metalstack_dot_api_dot_v2_dot_audit__pb2.AuditServiceListRequest, ctx: RequestContext) -> metalstack_dot_api_dot_v2_dot_audit__pb2.AuditServiceListResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class AuditServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: AuditServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/metalstack.api.v2.AuditService/Get": EndpointSync.unary(
                    method=MethodInfo(
                        name="Get",
                        service_name="metalstack.api.v2.AuditService",
                        input=metalstack_dot_api_dot_v2_dot_audit__pb2.AuditServiceGetRequest,
                        output=metalstack_dot_api_dot_v2_dot_audit__pb2.AuditServiceGetResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get,
                ),
                "/metalstack.api.v2.AuditService/List": EndpointSync.unary(
                    method=MethodInfo(
                        name="List",
                        service_name="metalstack.api.v2.AuditService",
                        input=metalstack_dot_api_dot_v2_dot_audit__pb2.AuditServiceListRequest,
                        output=metalstack_dot_api_dot_v2_dot_audit__pb2.AuditServiceListResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/metalstack.api.v2.AuditService"


class AuditServiceClientSync(ConnectClientSync):
    def get(
        self,
        request: metalstack_dot_api_dot_v2_dot_audit__pb2.AuditServiceGetRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> metalstack_dot_api_dot_v2_dot_audit__pb2.AuditServiceGetResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Get",
                service_name="metalstack.api.v2.AuditService",
                input=metalstack_dot_api_dot_v2_dot_audit__pb2.AuditServiceGetRequest,
                output=metalstack_dot_api_dot_v2_dot_audit__pb2.AuditServiceGetResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list(
        self,
        request: metalstack_dot_api_dot_v2_dot_audit__pb2.AuditServiceListRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> metalstack_dot_api_dot_v2_dot_audit__pb2.AuditServiceListResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="List",
                service_name="metalstack.api.v2.AuditService",
                input=metalstack_dot_api_dot_v2_dot_audit__pb2.AuditServiceListRequest,
                output=metalstack_dot_api_dot_v2_dot_audit__pb2.AuditServiceListResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
