// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: metalstack/admin/v2/image.proto

package adminv2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v2 "github.com/metal-stack/api/go/metalstack/api/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ImageServiceCreateRequest
type ImageServiceCreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Image is the image
	Image         *v2.Image `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageServiceCreateRequest) Reset() {
	*x = ImageServiceCreateRequest{}
	mi := &file_metalstack_admin_v2_image_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageServiceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageServiceCreateRequest) ProtoMessage() {}

func (x *ImageServiceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_admin_v2_image_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageServiceCreateRequest.ProtoReflect.Descriptor instead.
func (*ImageServiceCreateRequest) Descriptor() ([]byte, []int) {
	return file_metalstack_admin_v2_image_proto_rawDescGZIP(), []int{0}
}

func (x *ImageServiceCreateRequest) GetImage() *v2.Image {
	if x != nil {
		return x.Image
	}
	return nil
}

// ImageServiceCreateResponse
type ImageServiceCreateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Image is the image
	Image         *v2.Image `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageServiceCreateResponse) Reset() {
	*x = ImageServiceCreateResponse{}
	mi := &file_metalstack_admin_v2_image_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageServiceCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageServiceCreateResponse) ProtoMessage() {}

func (x *ImageServiceCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_admin_v2_image_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageServiceCreateResponse.ProtoReflect.Descriptor instead.
func (*ImageServiceCreateResponse) Descriptor() ([]byte, []int) {
	return file_metalstack_admin_v2_image_proto_rawDescGZIP(), []int{1}
}

func (x *ImageServiceCreateResponse) GetImage() *v2.Image {
	if x != nil {
		return x.Image
	}
	return nil
}

// ImageServiceUpdateRequest
type ImageServiceUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id of this image
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// UpdateMeta contains the timestamp and strategy to be used in this update request
	UpdateMeta *v2.UpdateMeta `protobuf:"bytes,2,opt,name=update_meta,json=updateMeta,proto3" json:"update_meta,omitempty"`
	// URL where this image is located
	Url *string `protobuf:"bytes,3,opt,name=url,proto3,oneof" json:"url,omitempty"`
	// Name of this imageLayout
	Name *string `protobuf:"bytes,4,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Description of this imageLayout
	Description *string `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Features of this image
	Features []v2.ImageFeature `protobuf:"varint,6,rep,packed,name=features,proto3,enum=metalstack.api.v2.ImageFeature" json:"features,omitempty"`
	// Classification of this image
	Classification v2.ImageClassification `protobuf:"varint,7,opt,name=classification,proto3,enum=metalstack.api.v2.ImageClassification" json:"classification,omitempty"`
	// ExpiresAt usage is not possible after this date
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageServiceUpdateRequest) Reset() {
	*x = ImageServiceUpdateRequest{}
	mi := &file_metalstack_admin_v2_image_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageServiceUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageServiceUpdateRequest) ProtoMessage() {}

func (x *ImageServiceUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_admin_v2_image_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageServiceUpdateRequest.ProtoReflect.Descriptor instead.
func (*ImageServiceUpdateRequest) Descriptor() ([]byte, []int) {
	return file_metalstack_admin_v2_image_proto_rawDescGZIP(), []int{2}
}

func (x *ImageServiceUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImageServiceUpdateRequest) GetUpdateMeta() *v2.UpdateMeta {
	if x != nil {
		return x.UpdateMeta
	}
	return nil
}

func (x *ImageServiceUpdateRequest) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *ImageServiceUpdateRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ImageServiceUpdateRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ImageServiceUpdateRequest) GetFeatures() []v2.ImageFeature {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *ImageServiceUpdateRequest) GetClassification() v2.ImageClassification {
	if x != nil {
		return x.Classification
	}
	return v2.ImageClassification(0)
}

func (x *ImageServiceUpdateRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// ImageServiceUpdateResponse
type ImageServiceUpdateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Image is the image
	Image         *v2.Image `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageServiceUpdateResponse) Reset() {
	*x = ImageServiceUpdateResponse{}
	mi := &file_metalstack_admin_v2_image_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageServiceUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageServiceUpdateResponse) ProtoMessage() {}

func (x *ImageServiceUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_admin_v2_image_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageServiceUpdateResponse.ProtoReflect.Descriptor instead.
func (*ImageServiceUpdateResponse) Descriptor() ([]byte, []int) {
	return file_metalstack_admin_v2_image_proto_rawDescGZIP(), []int{3}
}

func (x *ImageServiceUpdateResponse) GetImage() *v2.Image {
	if x != nil {
		return x.Image
	}
	return nil
}

// ImageServiceDeleteRequest
type ImageServiceDeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the image to delete
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageServiceDeleteRequest) Reset() {
	*x = ImageServiceDeleteRequest{}
	mi := &file_metalstack_admin_v2_image_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageServiceDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageServiceDeleteRequest) ProtoMessage() {}

func (x *ImageServiceDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_admin_v2_image_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageServiceDeleteRequest.ProtoReflect.Descriptor instead.
func (*ImageServiceDeleteRequest) Descriptor() ([]byte, []int) {
	return file_metalstack_admin_v2_image_proto_rawDescGZIP(), []int{4}
}

func (x *ImageServiceDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// message ImageServiceDeleteResponse {
type ImageServiceDeleteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ImageLayout the imagelayout
	Image         *v2.Image `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageServiceDeleteResponse) Reset() {
	*x = ImageServiceDeleteResponse{}
	mi := &file_metalstack_admin_v2_image_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageServiceDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageServiceDeleteResponse) ProtoMessage() {}

func (x *ImageServiceDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_admin_v2_image_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageServiceDeleteResponse.ProtoReflect.Descriptor instead.
func (*ImageServiceDeleteResponse) Descriptor() ([]byte, []int) {
	return file_metalstack_admin_v2_image_proto_rawDescGZIP(), []int{5}
}

func (x *ImageServiceDeleteResponse) GetImage() *v2.Image {
	if x != nil {
		return x.Image
	}
	return nil
}

// ImageServiceUsageRequest
type ImageServiceUsageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Query for which images the usage should be reported
	Query         *v2.ImageQuery `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageServiceUsageRequest) Reset() {
	*x = ImageServiceUsageRequest{}
	mi := &file_metalstack_admin_v2_image_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageServiceUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageServiceUsageRequest) ProtoMessage() {}

func (x *ImageServiceUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_admin_v2_image_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageServiceUsageRequest.ProtoReflect.Descriptor instead.
func (*ImageServiceUsageRequest) Descriptor() ([]byte, []int) {
	return file_metalstack_admin_v2_image_proto_rawDescGZIP(), []int{6}
}

func (x *ImageServiceUsageRequest) GetQuery() *v2.ImageQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

// ImageServiceUsageResponse
type ImageServiceUsageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Images with usage
	ImageUsage    []*v2.ImageUsage `protobuf:"bytes,1,rep,name=image_usage,json=imageUsage,proto3" json:"image_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageServiceUsageResponse) Reset() {
	*x = ImageServiceUsageResponse{}
	mi := &file_metalstack_admin_v2_image_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageServiceUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageServiceUsageResponse) ProtoMessage() {}

func (x *ImageServiceUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_admin_v2_image_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageServiceUsageResponse.ProtoReflect.Descriptor instead.
func (*ImageServiceUsageResponse) Descriptor() ([]byte, []int) {
	return file_metalstack_admin_v2_image_proto_rawDescGZIP(), []int{7}
}

func (x *ImageServiceUsageResponse) GetImageUsage() []*v2.ImageUsage {
	if x != nil {
		return x.ImageUsage
	}
	return nil
}

var File_metalstack_admin_v2_image_proto protoreflect.FileDescriptor

const file_metalstack_admin_v2_image_proto_rawDesc = "" +
	"\n" +
	"\x1fmetalstack/admin/v2/image.proto\x12\x13metalstack.admin.v2\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1emetalstack/api/v2/common.proto\x1a\x1dmetalstack/api/v2/image.proto\x1a(metalstack/api/v2/predefined_rules.proto\"K\n" +
	"\x19ImageServiceCreateRequest\x12.\n" +
	"\x05image\x18\x01 \x01(\v2\x18.metalstack.api.v2.ImageR\x05image\"L\n" +
	"\x1aImageServiceCreateResponse\x12.\n" +
	"\x05image\x18\x01 \x01(\v2\x18.metalstack.api.v2.ImageR\x05image\"\x81\x04\n" +
	"\x19ImageServiceUpdateRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x02\x18\x80\x01R\x02id\x12F\n" +
	"\vupdate_meta\x18\x02 \x01(\v2\x1d.metalstack.api.v2.UpdateMetaB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"updateMeta\x12\"\n" +
	"\x03url\x18\x03 \x01(\tB\v\xbaH\br\x06೮\xb1\x02\x01H\x00R\x03url\x88\x01\x01\x12$\n" +
	"\x04name\x18\x04 \x01(\tB\v\xbaH\br\x06\xc0\xb3\xae\xb1\x02\x01H\x01R\x04name\x88\x01\x01\x122\n" +
	"\vdescription\x18\x05 \x01(\tB\v\xbaH\br\x06ȳ\xae\xb1\x02\x01H\x02R\vdescription\x88\x01\x01\x12L\n" +
	"\bfeatures\x18\x06 \x03(\x0e2\x1f.metalstack.api.v2.ImageFeatureB\x0f\xbaH\f\x92\x01\t\x18\x01\"\x05\x82\x01\x02\x10\x01R\bfeatures\x12X\n" +
	"\x0eclassification\x18\a \x01(\x0e2&.metalstack.api.v2.ImageClassificationB\b\xbaH\x05\x82\x01\x02\x10\x01R\x0eclassification\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAtB\x06\n" +
	"\x04_urlB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_description\"L\n" +
	"\x1aImageServiceUpdateResponse\x12.\n" +
	"\x05image\x18\x01 \x01(\v2\x18.metalstack.api.v2.ImageR\x05image\"7\n" +
	"\x19ImageServiceDeleteRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x02\x18\x80\x01R\x02id\"L\n" +
	"\x1aImageServiceDeleteResponse\x12.\n" +
	"\x05image\x18\x01 \x01(\v2\x18.metalstack.api.v2.ImageR\x05image\"O\n" +
	"\x18ImageServiceUsageRequest\x123\n" +
	"\x05query\x18\x01 \x01(\v2\x1d.metalstack.api.v2.ImageQueryR\x05query\"[\n" +
	"\x19ImageServiceUsageResponse\x12>\n" +
	"\vimage_usage\x18\x01 \x03(\v2\x1d.metalstack.api.v2.ImageUsageR\n" +
	"imageUsage2\xe0\x03\n" +
	"\fImageService\x12t\n" +
	"\x06Create\x12..metalstack.admin.v2.ImageServiceCreateRequest\x1a/.metalstack.admin.v2.ImageServiceCreateResponse\"\t\xd2\xf3\x18\x01\x01\xe0\xf3\x18\x01\x12t\n" +
	"\x06Update\x12..metalstack.admin.v2.ImageServiceUpdateRequest\x1a/.metalstack.admin.v2.ImageServiceUpdateResponse\"\t\xd2\xf3\x18\x01\x01\xe0\xf3\x18\x01\x12t\n" +
	"\x06Delete\x12..metalstack.admin.v2.ImageServiceDeleteRequest\x1a/.metalstack.admin.v2.ImageServiceDeleteResponse\"\t\xd2\xf3\x18\x01\x01\xe0\xf3\x18\x01\x12n\n" +
	"\x05Usage\x12-.metalstack.admin.v2.ImageServiceUsageRequest\x1a..metalstack.admin.v2.ImageServiceUsageResponse\"\x06\xd2\xf3\x18\x02\x01\x02B\xce\x01\n" +
	"\x17com.metalstack.admin.v2B\n" +
	"ImageProtoP\x01Z9github.com/metal-stack/api/go/metalstack/admin/v2;adminv2\xa2\x02\x03MAX\xaa\x02\x13Metalstack.Admin.V2\xca\x02\x13Metalstack\\Admin\\V2\xe2\x02\x1fMetalstack\\Admin\\V2\\GPBMetadata\xea\x02\x15Metalstack::Admin::V2b\x06proto3"

var (
	file_metalstack_admin_v2_image_proto_rawDescOnce sync.Once
	file_metalstack_admin_v2_image_proto_rawDescData []byte
)

func file_metalstack_admin_v2_image_proto_rawDescGZIP() []byte {
	file_metalstack_admin_v2_image_proto_rawDescOnce.Do(func() {
		file_metalstack_admin_v2_image_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metalstack_admin_v2_image_proto_rawDesc), len(file_metalstack_admin_v2_image_proto_rawDesc)))
	})
	return file_metalstack_admin_v2_image_proto_rawDescData
}

var file_metalstack_admin_v2_image_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_metalstack_admin_v2_image_proto_goTypes = []any{
	(*ImageServiceCreateRequest)(nil),  // 0: metalstack.admin.v2.ImageServiceCreateRequest
	(*ImageServiceCreateResponse)(nil), // 1: metalstack.admin.v2.ImageServiceCreateResponse
	(*ImageServiceUpdateRequest)(nil),  // 2: metalstack.admin.v2.ImageServiceUpdateRequest
	(*ImageServiceUpdateResponse)(nil), // 3: metalstack.admin.v2.ImageServiceUpdateResponse
	(*ImageServiceDeleteRequest)(nil),  // 4: metalstack.admin.v2.ImageServiceDeleteRequest
	(*ImageServiceDeleteResponse)(nil), // 5: metalstack.admin.v2.ImageServiceDeleteResponse
	(*ImageServiceUsageRequest)(nil),   // 6: metalstack.admin.v2.ImageServiceUsageRequest
	(*ImageServiceUsageResponse)(nil),  // 7: metalstack.admin.v2.ImageServiceUsageResponse
	(*v2.Image)(nil),                   // 8: metalstack.api.v2.Image
	(*v2.UpdateMeta)(nil),              // 9: metalstack.api.v2.UpdateMeta
	(v2.ImageFeature)(0),               // 10: metalstack.api.v2.ImageFeature
	(v2.ImageClassification)(0),        // 11: metalstack.api.v2.ImageClassification
	(*timestamppb.Timestamp)(nil),      // 12: google.protobuf.Timestamp
	(*v2.ImageQuery)(nil),              // 13: metalstack.api.v2.ImageQuery
	(*v2.ImageUsage)(nil),              // 14: metalstack.api.v2.ImageUsage
}
var file_metalstack_admin_v2_image_proto_depIdxs = []int32{
	8,  // 0: metalstack.admin.v2.ImageServiceCreateRequest.image:type_name -> metalstack.api.v2.Image
	8,  // 1: metalstack.admin.v2.ImageServiceCreateResponse.image:type_name -> metalstack.api.v2.Image
	9,  // 2: metalstack.admin.v2.ImageServiceUpdateRequest.update_meta:type_name -> metalstack.api.v2.UpdateMeta
	10, // 3: metalstack.admin.v2.ImageServiceUpdateRequest.features:type_name -> metalstack.api.v2.ImageFeature
	11, // 4: metalstack.admin.v2.ImageServiceUpdateRequest.classification:type_name -> metalstack.api.v2.ImageClassification
	12, // 5: metalstack.admin.v2.ImageServiceUpdateRequest.expires_at:type_name -> google.protobuf.Timestamp
	8,  // 6: metalstack.admin.v2.ImageServiceUpdateResponse.image:type_name -> metalstack.api.v2.Image
	8,  // 7: metalstack.admin.v2.ImageServiceDeleteResponse.image:type_name -> metalstack.api.v2.Image
	13, // 8: metalstack.admin.v2.ImageServiceUsageRequest.query:type_name -> metalstack.api.v2.ImageQuery
	14, // 9: metalstack.admin.v2.ImageServiceUsageResponse.image_usage:type_name -> metalstack.api.v2.ImageUsage
	0,  // 10: metalstack.admin.v2.ImageService.Create:input_type -> metalstack.admin.v2.ImageServiceCreateRequest
	2,  // 11: metalstack.admin.v2.ImageService.Update:input_type -> metalstack.admin.v2.ImageServiceUpdateRequest
	4,  // 12: metalstack.admin.v2.ImageService.Delete:input_type -> metalstack.admin.v2.ImageServiceDeleteRequest
	6,  // 13: metalstack.admin.v2.ImageService.Usage:input_type -> metalstack.admin.v2.ImageServiceUsageRequest
	1,  // 14: metalstack.admin.v2.ImageService.Create:output_type -> metalstack.admin.v2.ImageServiceCreateResponse
	3,  // 15: metalstack.admin.v2.ImageService.Update:output_type -> metalstack.admin.v2.ImageServiceUpdateResponse
	5,  // 16: metalstack.admin.v2.ImageService.Delete:output_type -> metalstack.admin.v2.ImageServiceDeleteResponse
	7,  // 17: metalstack.admin.v2.ImageService.Usage:output_type -> metalstack.admin.v2.ImageServiceUsageResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_metalstack_admin_v2_image_proto_init() }
func file_metalstack_admin_v2_image_proto_init() {
	if File_metalstack_admin_v2_image_proto != nil {
		return
	}
	file_metalstack_admin_v2_image_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metalstack_admin_v2_image_proto_rawDesc), len(file_metalstack_admin_v2_image_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metalstack_admin_v2_image_proto_goTypes,
		DependencyIndexes: file_metalstack_admin_v2_image_proto_depIdxs,
		MessageInfos:      file_metalstack_admin_v2_image_proto_msgTypes,
	}.Build()
	File_metalstack_admin_v2_image_proto = out.File
	file_metalstack_admin_v2_image_proto_goTypes = nil
	file_metalstack_admin_v2_image_proto_depIdxs = nil
}
