// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: metalstack/api/v2/size.proto

package apiv2connect

import (
	connect "connectrpc.com/connect/v2"
	context "context"
	v2 "github.com/metal-stack/api/go/metalstack/api/v2"
	sync "sync"
)

const (
	// SizeServiceName is the fully-qualified name of the SizeService service.
	SizeServiceName = "metalstack.api.v2.SizeService"
)

// These constants are the procedure names of the RPCs defined in this package. They're exposed at
// runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SizeServiceGetProcedure is the procedure name of the SizeService's Get RPC.
	SizeServiceGetProcedure = "/metalstack.api.v2.SizeService/Get"
	// SizeServiceListProcedure is the procedure name of the SizeService's List RPC.
	SizeServiceListProcedure = "/metalstack.api.v2.SizeService/List"
)

var (
	sizeServiceGetSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v2.File_metalstack_api_v2_size_proto.Services().ByName("SizeService").Methods().ByName("Get"),
			Procedure:  SizeServiceGetProcedure,
		}
	})
	sizeServiceListSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v2.File_metalstack_api_v2_size_proto.Services().ByName("SizeService").Methods().ByName("List"),
			Procedure:  SizeServiceListProcedure,
		}
	})
)

// SizeServiceClient is a client for the metalstack.api.v2.SizeService service.
type SizeServiceClient interface {
	// Returns the size with the specified ID.
	Get(context.Context, *v2.SizeServiceGetRequest) (*v2.SizeServiceGetResponse, error)
	// Returns the list of all sizes.
	List(context.Context, *v2.SizeServiceListRequest) (*v2.SizeServiceListResponse, error)
}

// NewSizeServiceClient constructs a client for the metalstack.api.v2.SizeService service. Multiple
// service clients may share a single connect.Client.
func NewSizeServiceClient(client *connect.Client) SizeServiceClient {
	return &sizeServiceClient{client: client}
}

// SizeServiceHandler is an implementation of the metalstack.api.v2.SizeService service.
type SizeServiceHandler interface {
	// Returns the size with the specified ID.
	Get(context.Context, *v2.SizeServiceGetRequest) (*v2.SizeServiceGetResponse, error)
	// Returns the list of all sizes.
	List(context.Context, *v2.SizeServiceListRequest) (*v2.SizeServiceListResponse, error)
}

// RegisterSizeServiceHandler registers svc as the metalstack.api.v2.SizeService implementation on
// server.
func RegisterSizeServiceHandler(server *connect.Server, svc SizeServiceHandler) {
	adapter := sizeServiceHandler{svc: svc}
	server.Register(
		connect.Method{Spec: sizeServiceGetSpec(), Handler: adapter.get},
		connect.Method{Spec: sizeServiceListSpec(), Handler: adapter.list},
	)
}

// UnimplementedSizeServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSizeServiceHandler struct{}

func (UnimplementedSizeServiceHandler) Get(context.Context, *v2.SizeServiceGetRequest) (*v2.SizeServiceGetResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "metalstack.api.v2.SizeService.Get is not implemented")
}

func (UnimplementedSizeServiceHandler) List(context.Context, *v2.SizeServiceListRequest) (*v2.SizeServiceListResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "metalstack.api.v2.SizeService.List is not implemented")
}

type sizeServiceClient struct {
	client *connect.Client
}

func (c *sizeServiceClient) Get(ctx context.Context, req *v2.SizeServiceGetRequest) (*v2.SizeServiceGetResponse, error) {
	var res v2.SizeServiceGetResponse
	if err := c.client.CallUnary(ctx, sizeServiceGetSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *sizeServiceClient) List(ctx context.Context, req *v2.SizeServiceListRequest) (*v2.SizeServiceListResponse, error) {
	var res v2.SizeServiceListResponse
	if err := c.client.CallUnary(ctx, sizeServiceListSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

type sizeServiceHandler struct{ svc SizeServiceHandler }

func (h sizeServiceHandler) get(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v2.SizeServiceGetRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.Get(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h sizeServiceHandler) list(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v2.SizeServiceListRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.List(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}
