// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: metalstack/api/v2/project.proto

package apiv2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Project defines a group of resources belonging to a tenant
// a tenant can have multiple projects
type Project struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Uuid of this project
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Meta for this ip
	Meta *Meta `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	// Name of this project must be unique per tenant
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Description of this project
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Tenant this project belongs to
	Tenant string `protobuf:"bytes,5,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// AvatarUrl of the Project
	AvatarUrl     *string `protobuf:"bytes,6,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_metalstack_api_v2_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_api_v2_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_metalstack_api_v2_project_proto_rawDescGZIP(), []int{0}
}

func (x *Project) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Project) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *Project) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

// ProjectMember defines a user that participates at a project
type ProjectMember struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id is the user id of the member
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Role is the role of the member
	Role ProjectRole `protobuf:"varint,2,opt,name=role,proto3,enum=metalstack.api.v2.ProjectRole" json:"role,omitempty"`
	// InheritedMembership indicates that this member has implicit permissions on the project through his membership within the tenant.
	// This member does not have direct project membership but gains permissions on this project from the role he has in the tenant.
	// Inherited memberships are not included in member lists for users with guest permission but only for direct tenant members.
	InheritedMembership bool `protobuf:"varint,3,opt,name=inherited_membership,json=inheritedMembership,proto3" json:"inherited_membership,omitempty"`
	// CreatedAt the date when the member was added to the project
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMember) Reset() {
	*x = ProjectMember{}
	mi := &file_metalstack_api_v2_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMember) ProtoMessage() {}

func (x *ProjectMember) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_api_v2_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMember.ProtoReflect.Descriptor instead.
func (*ProjectMember) Descriptor() ([]byte, []int) {
	return file_metalstack_api_v2_project_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectMember) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProjectMember) GetRole() ProjectRole {
	if x != nil {
		return x.Role
	}
	return ProjectRole_PROJECT_ROLE_UNSPECIFIED
}

func (x *ProjectMember) GetInheritedMembership() bool {
	if x != nil {
		return x.InheritedMembership
	}
	return false
}

func (x *ProjectMember) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// ProjectInvite defines invite to project
type ProjectInvite struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Secret is the secret part of the invite, typically part of the url
	Secret string `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	// Project is the project id for which this invite was created
	Project string `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	// Role is the role in this project the user will get after accepting the invitation
	Role ProjectRole `protobuf:"varint,3,opt,name=role,proto3,enum=metalstack.api.v2.ProjectRole" json:"role,omitempty"`
	// Joined is false as long as a user has not accepted the invite
	Joined bool `protobuf:"varint,4,opt,name=joined,proto3" json:"joined,omitempty"`
	// ProjectName is the project name for which this invite was created
	ProjectName string `protobuf:"bytes,5,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	// Tenant is the login of tenant who invites to join this project
	Tenant string `protobuf:"bytes,6,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// TenantName is the name of tenant who invites to join this project
	TenantName string `protobuf:"bytes,7,opt,name=tenant_name,json=tenantName,proto3" json:"tenant_name,omitempty"`
	// ExpiresAt the date when this invite expires
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// JoinedAt the date when the member accepted this invite
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectInvite) Reset() {
	*x = ProjectInvite{}
	mi := &file_metalstack_api_v2_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectInvite) ProtoMessage() {}

func (x *ProjectInvite) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_api_v2_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectInvite.ProtoReflect.Descriptor instead.
func (*ProjectInvite) Descriptor() ([]byte, []int) {
	return file_metalstack_api_v2_project_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectInvite) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *ProjectInvite) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ProjectInvite) GetRole() ProjectRole {
	if x != nil {
		return x.Role
	}
	return ProjectRole_PROJECT_ROLE_UNSPECIFIED
}

func (x *ProjectInvite) GetJoined() bool {
	if x != nil {
		return x.Joined
	}
	return false
}

func (x *ProjectInvite) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *ProjectInvite) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *ProjectInvite) GetTenantName() string {
	if x != nil {
		return x.TenantName
	}
	return ""
}

func (x *ProjectInvite) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ProjectInvite) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

// ProjectServiceListRequest is the request payload to list all projects
type ProjectServiceListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name list only projects with this name
	Name *string `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Tenant list only projects of this tenant
	Tenant        *string `protobuf:"bytes,2,opt,name=tenant,proto3,oneof" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceListRequest) Reset() {
	*x = ProjectServiceListRequest{}
	mi := &file_metalstack_api_v2_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceListRequest) ProtoMessage() {}

func (x *ProjectServiceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_api_v2_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceListRequest.ProtoReflect.Descriptor instead.
func (*ProjectServiceListRequest) Descriptor() ([]byte, []int) {
	return file_metalstack_api_v2_project_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectServiceListRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ProjectServiceListRequest) GetTenant() string {
	if x != nil && x.Tenant != nil {
		return *x.Tenant
	}
	return ""
}

// ProjectServiceListResponse is the response payload to list all projects
type ProjectServiceListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Projects is a list of all your projects
	Projects      []*Project `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceListResponse) Reset() {
	*x = ProjectServiceListResponse{}
	mi := &file_metalstack_api_v2_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceListResponse) ProtoMessage() {}

func (x *ProjectServiceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_api_v2_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceListResponse.ProtoReflect.Descriptor instead.
func (*ProjectServiceListResponse) Descriptor() ([]byte, []int) {
	return file_metalstack_api_v2_project_proto_rawDescGZIP(), []int{4}
}

func (x *ProjectServiceListResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

// ProjectServiceGetRequest is the request payload to get a project
type ProjectServiceGetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project is the uuid of the project to get
	Project       string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceGetRequest) Reset() {
	*x = ProjectServiceGetRequest{}
	mi := &file_metalstack_api_v2_project_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceGetRequest) ProtoMessage() {}

func (x *ProjectServiceGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_api_v2_project_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceGetRequest.ProtoReflect.Descriptor instead.
func (*ProjectServiceGetRequest) Descriptor() ([]byte, []int) {
	return file_metalstack_api_v2_project_proto_rawDescGZIP(), []int{5}
}

func (x *ProjectServiceGetRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

// ProjectServiceGetResponse is the response payload to get a projects
type ProjectServiceGetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project is the project
	Project *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	// ProjectMembers in this project, projects guests will only see direct project members and not implicit memberships from tenant permissions
	ProjectMembers []*ProjectMember `protobuf:"bytes,2,rep,name=project_members,json=projectMembers,proto3" json:"project_members,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProjectServiceGetResponse) Reset() {
	*x = ProjectServiceGetResponse{}
	mi := &file_metalstack_api_v2_project_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceGetResponse) ProtoMessage() {}

func (x *ProjectServiceGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_api_v2_project_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceGetResponse.ProtoReflect.Descriptor instead.
func (*ProjectServiceGetResponse) Descriptor() ([]byte, []int) {
	return file_metalstack_api_v2_project_proto_rawDescGZIP(), []int{6}
}

func (x *ProjectServiceGetResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *ProjectServiceGetResponse) GetProjectMembers() []*ProjectMember {
	if x != nil {
		return x.ProjectMembers
	}
	return nil
}

// ProjectServiceCreateRequest is the request payload to Create a project
type ProjectServiceCreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Login is the tenant of this project
	// TODO: is login really a good name?
	Login string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	// Name of this project, unique per tenant
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Description of this project
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Avatar URL of the project
	AvatarUrl     *string `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceCreateRequest) Reset() {
	*x = ProjectServiceCreateRequest{}
	mi := &file_metalstack_api_v2_project_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceCreateRequest) ProtoMessage() {}

func (x *ProjectServiceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_api_v2_project_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceCreateRequest.ProtoReflect.Descriptor instead.
func (*ProjectServiceCreateRequest) Descriptor() ([]byte, []int) {
	return file_metalstack_api_v2_project_proto_rawDescGZIP(), []int{7}
}

func (x *ProjectServiceCreateRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *ProjectServiceCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectServiceCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProjectServiceCreateRequest) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

// ProjectServiceCreateResponse is the response payload of creation of a project
type ProjectServiceCreateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project is the project
	Project       *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceCreateResponse) Reset() {
	*x = ProjectServiceCreateResponse{}
	mi := &file_metalstack_api_v2_project_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceCreateResponse) ProtoMessage() {}

func (x *ProjectServiceCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_api_v2_project_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceCreateResponse.ProtoReflect.Descriptor instead.
func (*ProjectServiceCreateResponse) Descriptor() ([]byte, []int) {
	return file_metalstack_api_v2_project_proto_rawDescGZIP(), []int{8}
}

func (x *ProjectServiceCreateResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

// ProjectServiceDeleteRequest is the request payload to delete a project
type ProjectServiceDeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project is the uuid of the project to get
	Project       string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceDeleteRequest) Reset() {
	*x = ProjectServiceDeleteRequest{}
	mi := &file_metalstack_api_v2_project_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceDeleteRequest) ProtoMessage() {}

func (x *ProjectServiceDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_api_v2_project_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceDeleteRequest.ProtoReflect.Descriptor instead.
func (*ProjectServiceDeleteRequest) Descriptor() ([]byte, []int) {
	return file_metalstack_api_v2_project_proto_rawDescGZIP(), []int{9}
}

func (x *ProjectServiceDeleteRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

// ProjectServiceDeleteResponse is the response payload to delete a project
type ProjectServiceDeleteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project is the project
	Project       *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceDeleteResponse) Reset() {
	*x = ProjectServiceDeleteResponse{}
	mi := &file_metalstack_api_v2_project_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceDeleteResponse) ProtoMessage() {}

func (x *ProjectServiceDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_api_v2_project_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceDeleteResponse.ProtoReflect.Descriptor instead.
func (*ProjectServiceDeleteResponse) Descriptor() ([]byte, []int) {
	return file_metalstack_api_v2_project_proto_rawDescGZIP(), []int{10}
}

func (x *ProjectServiceDeleteResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

// ProjectServiceUpdateRequest is the request payload to update a project
type ProjectServiceUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project is the uuid of the project to get
	Project string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	// Name of this project unique per tenant
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Description of this project
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Avatar URL of the project
	AvatarUrl     *string `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceUpdateRequest) Reset() {
	*x = ProjectServiceUpdateRequest{}
	mi := &file_metalstack_api_v2_project_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceUpdateRequest) ProtoMessage() {}

func (x *ProjectServiceUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_api_v2_project_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceUpdateRequest.ProtoReflect.Descriptor instead.
func (*ProjectServiceUpdateRequest) Descriptor() ([]byte, []int) {
	return file_metalstack_api_v2_project_proto_rawDescGZIP(), []int{11}
}

func (x *ProjectServiceUpdateRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ProjectServiceUpdateRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ProjectServiceUpdateRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ProjectServiceUpdateRequest) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

// ProjectServiceUpdateResponse is the response payload to update a project
type ProjectServiceUpdateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project is the project
	Project       *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceUpdateResponse) Reset() {
	*x = ProjectServiceUpdateResponse{}
	mi := &file_metalstack_api_v2_project_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceUpdateResponse) ProtoMessage() {}

func (x *ProjectServiceUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_api_v2_project_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceUpdateResponse.ProtoReflect.Descriptor instead.
func (*ProjectServiceUpdateResponse) Descriptor() ([]byte, []int) {
	return file_metalstack_api_v2_project_proto_rawDescGZIP(), []int{12}
}

func (x *ProjectServiceUpdateResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

// ProjectServiceInviteRequest is used to invite a member to a project
type ProjectServiceInviteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project is the uuid of the project
	Project string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	// Role of this user in this project
	Role          ProjectRole `protobuf:"varint,3,opt,name=role,proto3,enum=metalstack.api.v2.ProjectRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceInviteRequest) Reset() {
	*x = ProjectServiceInviteRequest{}
	mi := &file_metalstack_api_v2_project_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceInviteRequest) ProtoMessage() {}

func (x *ProjectServiceInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_api_v2_project_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceInviteRequest.ProtoReflect.Descriptor instead.
func (*ProjectServiceInviteRequest) Descriptor() ([]byte, []int) {
	return file_metalstack_api_v2_project_proto_rawDescGZIP(), []int{13}
}

func (x *ProjectServiceInviteRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ProjectServiceInviteRequest) GetRole() ProjectRole {
	if x != nil {
		return x.Role
	}
	return ProjectRole_PROJECT_ROLE_UNSPECIFIED
}

// ProjectServiceInviteRequest is the response payload to a invite member request
type ProjectServiceInviteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Inviter contains a secret which can be sent to a potential user
	// can be appended to the invitation endpoint at our cloud console like
	// console.metalstack.cloud/invite/<secret>
	Invite        *ProjectInvite `protobuf:"bytes,1,opt,name=invite,proto3" json:"invite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceInviteResponse) Reset() {
	*x = ProjectServiceInviteResponse{}
	mi := &file_metalstack_api_v2_project_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceInviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceInviteResponse) ProtoMessage() {}

func (x *ProjectServiceInviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_api_v2_project_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceInviteResponse.ProtoReflect.Descriptor instead.
func (*ProjectServiceInviteResponse) Descriptor() ([]byte, []int) {
	return file_metalstack_api_v2_project_proto_rawDescGZIP(), []int{14}
}

func (x *ProjectServiceInviteResponse) GetInvite() *ProjectInvite {
	if x != nil {
		return x.Invite
	}
	return nil
}

// ProjectServiceInvitesListRequest is the request payload to a list invites request
type ProjectServiceInvitesListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project is the uuid of the project
	Project       string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceInvitesListRequest) Reset() {
	*x = ProjectServiceInvitesListRequest{}
	mi := &file_metalstack_api_v2_project_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceInvitesListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceInvitesListRequest) ProtoMessage() {}

func (x *ProjectServiceInvitesListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_api_v2_project_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceInvitesListRequest.ProtoReflect.Descriptor instead.
func (*ProjectServiceInvitesListRequest) Descriptor() ([]byte, []int) {
	return file_metalstack_api_v2_project_proto_rawDescGZIP(), []int{15}
}

func (x *ProjectServiceInvitesListRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

// ProjectServiceInvitesListResponse is the response payload to a list invites request
type ProjectServiceInvitesListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Invites not already accepted the invitation to this project
	Invites       []*ProjectInvite `protobuf:"bytes,1,rep,name=invites,proto3" json:"invites,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceInvitesListResponse) Reset() {
	*x = ProjectServiceInvitesListResponse{}
	mi := &file_metalstack_api_v2_project_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceInvitesListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceInvitesListResponse) ProtoMessage() {}

func (x *ProjectServiceInvitesListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_api_v2_project_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceInvitesListResponse.ProtoReflect.Descriptor instead.
func (*ProjectServiceInvitesListResponse) Descriptor() ([]byte, []int) {
	return file_metalstack_api_v2_project_proto_rawDescGZIP(), []int{16}
}

func (x *ProjectServiceInvitesListResponse) GetInvites() []*ProjectInvite {
	if x != nil {
		return x.Invites
	}
	return nil
}

// ProjectServiceInviteGetRequest is the request payload to get a invite
type ProjectServiceInviteGetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Secret of the invite to list
	Secret        string `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceInviteGetRequest) Reset() {
	*x = ProjectServiceInviteGetRequest{}
	mi := &file_metalstack_api_v2_project_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceInviteGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceInviteGetRequest) ProtoMessage() {}

func (x *ProjectServiceInviteGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_api_v2_project_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceInviteGetRequest.ProtoReflect.Descriptor instead.
func (*ProjectServiceInviteGetRequest) Descriptor() ([]byte, []int) {
	return file_metalstack_api_v2_project_proto_rawDescGZIP(), []int{17}
}

func (x *ProjectServiceInviteGetRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

// ProjectServiceInviteGetResponse is the response payload to a get invite request
type ProjectServiceInviteGetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Invite is the invite
	Invite        *ProjectInvite `protobuf:"bytes,1,opt,name=invite,proto3" json:"invite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceInviteGetResponse) Reset() {
	*x = ProjectServiceInviteGetResponse{}
	mi := &file_metalstack_api_v2_project_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceInviteGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceInviteGetResponse) ProtoMessage() {}

func (x *ProjectServiceInviteGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_api_v2_project_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceInviteGetResponse.ProtoReflect.Descriptor instead.
func (*ProjectServiceInviteGetResponse) Descriptor() ([]byte, []int) {
	return file_metalstack_api_v2_project_proto_rawDescGZIP(), []int{18}
}

func (x *ProjectServiceInviteGetResponse) GetInvite() *ProjectInvite {
	if x != nil {
		return x.Invite
	}
	return nil
}

// ProjectServiceRemoveMemberRequest is used to remove a member from a project
type ProjectServiceRemoveMemberRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project is the uuid of the project
	Project string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	// MemberID is the id of the member to remove from this project
	MemberId      string `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceRemoveMemberRequest) Reset() {
	*x = ProjectServiceRemoveMemberRequest{}
	mi := &file_metalstack_api_v2_project_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceRemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceRemoveMemberRequest) ProtoMessage() {}

func (x *ProjectServiceRemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_api_v2_project_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceRemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*ProjectServiceRemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_metalstack_api_v2_project_proto_rawDescGZIP(), []int{19}
}

func (x *ProjectServiceRemoveMemberRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ProjectServiceRemoveMemberRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

// ProjectServiceRemoveMemberResponse is the response payload to a remove member request
type ProjectServiceRemoveMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceRemoveMemberResponse) Reset() {
	*x = ProjectServiceRemoveMemberResponse{}
	mi := &file_metalstack_api_v2_project_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceRemoveMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceRemoveMemberResponse) ProtoMessage() {}

func (x *ProjectServiceRemoveMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_api_v2_project_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceRemoveMemberResponse.ProtoReflect.Descriptor instead.
func (*ProjectServiceRemoveMemberResponse) Descriptor() ([]byte, []int) {
	return file_metalstack_api_v2_project_proto_rawDescGZIP(), []int{20}
}

// ProjectServiceUpdateMemberRequest is used to update a member of a project
type ProjectServiceUpdateMemberRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project is the uuid of the project
	Project string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	// MemberID is the id of the member to remove from this project
	MemberId string `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	// Role is the role in this project the user will get after the update
	Role          ProjectRole `protobuf:"varint,3,opt,name=role,proto3,enum=metalstack.api.v2.ProjectRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceUpdateMemberRequest) Reset() {
	*x = ProjectServiceUpdateMemberRequest{}
	mi := &file_metalstack_api_v2_project_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceUpdateMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceUpdateMemberRequest) ProtoMessage() {}

func (x *ProjectServiceUpdateMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_api_v2_project_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceUpdateMemberRequest.ProtoReflect.Descriptor instead.
func (*ProjectServiceUpdateMemberRequest) Descriptor() ([]byte, []int) {
	return file_metalstack_api_v2_project_proto_rawDescGZIP(), []int{21}
}

func (x *ProjectServiceUpdateMemberRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ProjectServiceUpdateMemberRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *ProjectServiceUpdateMemberRequest) GetRole() ProjectRole {
	if x != nil {
		return x.Role
	}
	return ProjectRole_PROJECT_ROLE_UNSPECIFIED
}

// ProjectServiceUpdateMemberResponse is the response payload to a update member request
type ProjectServiceUpdateMemberResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ProjectMember is the updated project member
	ProjectMember *ProjectMember `protobuf:"bytes,5,opt,name=project_member,json=projectMember,proto3" json:"project_member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceUpdateMemberResponse) Reset() {
	*x = ProjectServiceUpdateMemberResponse{}
	mi := &file_metalstack_api_v2_project_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceUpdateMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceUpdateMemberResponse) ProtoMessage() {}

func (x *ProjectServiceUpdateMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_api_v2_project_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceUpdateMemberResponse.ProtoReflect.Descriptor instead.
func (*ProjectServiceUpdateMemberResponse) Descriptor() ([]byte, []int) {
	return file_metalstack_api_v2_project_proto_rawDescGZIP(), []int{22}
}

func (x *ProjectServiceUpdateMemberResponse) GetProjectMember() *ProjectMember {
	if x != nil {
		return x.ProjectMember
	}
	return nil
}

// ProjectServiceInviteAcceptRequest is the request payload to a accept invite request
type ProjectServiceInviteAcceptRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Secret is the invitation secret part of the invitation url
	Secret        string `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceInviteAcceptRequest) Reset() {
	*x = ProjectServiceInviteAcceptRequest{}
	mi := &file_metalstack_api_v2_project_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceInviteAcceptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceInviteAcceptRequest) ProtoMessage() {}

func (x *ProjectServiceInviteAcceptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_api_v2_project_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceInviteAcceptRequest.ProtoReflect.Descriptor instead.
func (*ProjectServiceInviteAcceptRequest) Descriptor() ([]byte, []int) {
	return file_metalstack_api_v2_project_proto_rawDescGZIP(), []int{23}
}

func (x *ProjectServiceInviteAcceptRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

// ProjectServiceInvitesListResponse is the response payload to a accept invite request
type ProjectServiceInviteAcceptResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project ID of the project joined
	Project string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	// ProjectName if the project joined
	ProjectName   string `protobuf:"bytes,2,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceInviteAcceptResponse) Reset() {
	*x = ProjectServiceInviteAcceptResponse{}
	mi := &file_metalstack_api_v2_project_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceInviteAcceptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceInviteAcceptResponse) ProtoMessage() {}

func (x *ProjectServiceInviteAcceptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_api_v2_project_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceInviteAcceptResponse.ProtoReflect.Descriptor instead.
func (*ProjectServiceInviteAcceptResponse) Descriptor() ([]byte, []int) {
	return file_metalstack_api_v2_project_proto_rawDescGZIP(), []int{24}
}

func (x *ProjectServiceInviteAcceptResponse) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ProjectServiceInviteAcceptResponse) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

// ProjectServiceInviteDeleteRequest is the request payload to a delete invite
type ProjectServiceInviteDeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project is the uuid of the project
	Project string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	// Secret of the invite to delete
	Secret        string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceInviteDeleteRequest) Reset() {
	*x = ProjectServiceInviteDeleteRequest{}
	mi := &file_metalstack_api_v2_project_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceInviteDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceInviteDeleteRequest) ProtoMessage() {}

func (x *ProjectServiceInviteDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_api_v2_project_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceInviteDeleteRequest.ProtoReflect.Descriptor instead.
func (*ProjectServiceInviteDeleteRequest) Descriptor() ([]byte, []int) {
	return file_metalstack_api_v2_project_proto_rawDescGZIP(), []int{25}
}

func (x *ProjectServiceInviteDeleteRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ProjectServiceInviteDeleteRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

// ProjectServiceInviteDeleteResponse is the response payload of a delete invite request
type ProjectServiceInviteDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceInviteDeleteResponse) Reset() {
	*x = ProjectServiceInviteDeleteResponse{}
	mi := &file_metalstack_api_v2_project_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceInviteDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceInviteDeleteResponse) ProtoMessage() {}

func (x *ProjectServiceInviteDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metalstack_api_v2_project_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceInviteDeleteResponse.ProtoReflect.Descriptor instead.
func (*ProjectServiceInviteDeleteResponse) Descriptor() ([]byte, []int) {
	return file_metalstack_api_v2_project_proto_rawDescGZIP(), []int{26}
}

var File_metalstack_api_v2_project_proto protoreflect.FileDescriptor

const file_metalstack_api_v2_project_proto_rawDesc = "" +
	"\n" +
	"\x1fmetalstack/api/v2/project.proto\x12\x11metalstack.api.v2\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1emetalstack/api/v2/common.proto\"\xcb\x01\n" +
	"\aProject\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12+\n" +
	"\x04meta\x18\x02 \x01(\v2\x17.metalstack.api.v2.MetaR\x04meta\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06tenant\x18\x05 \x01(\tR\x06tenant\x12\"\n" +
	"\n" +
	"avatar_url\x18\x06 \x01(\tH\x00R\tavatarUrl\x88\x01\x01B\r\n" +
	"\v_avatar_url\"\xcb\x01\n" +
	"\rProjectMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12<\n" +
	"\x04role\x18\x02 \x01(\x0e2\x1e.metalstack.api.v2.ProjectRoleB\b\xbaH\x05\x82\x01\x02\x10\x01R\x04role\x121\n" +
	"\x14inherited_membership\x18\x03 \x01(\bR\x13inheritedMembership\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xe7\x02\n" +
	"\rProjectInvite\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12<\n" +
	"\x04role\x18\x03 \x01(\x0e2\x1e.metalstack.api.v2.ProjectRoleB\b\xbaH\x05\x82\x01\x02\x10\x01R\x04role\x12\x16\n" +
	"\x06joined\x18\x04 \x01(\bR\x06joined\x12!\n" +
	"\fproject_name\x18\x05 \x01(\tR\vprojectName\x12\x16\n" +
	"\x06tenant\x18\x06 \x01(\tR\x06tenant\x12\x1f\n" +
	"\vtenant_name\x18\a \x01(\tR\n" +
	"tenantName\x129\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x127\n" +
	"\tjoined_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\"}\n" +
	"\x19ProjectServiceListRequest\x12#\n" +
	"\x04name\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x02\x18\x80\x01H\x00R\x04name\x88\x01\x01\x12'\n" +
	"\x06tenant\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x02\x18\x80\x01H\x01R\x06tenant\x88\x01\x01B\a\n" +
	"\x05_nameB\t\n" +
	"\a_tenant\"T\n" +
	"\x1aProjectServiceListResponse\x126\n" +
	"\bprojects\x18\x01 \x03(\v2\x1a.metalstack.api.v2.ProjectR\bprojects\">\n" +
	"\x18ProjectServiceGetRequest\x12\"\n" +
	"\aproject\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aproject\"\x9c\x01\n" +
	"\x19ProjectServiceGetResponse\x124\n" +
	"\aproject\x18\x01 \x01(\v2\x1a.metalstack.api.v2.ProjectR\aproject\x12I\n" +
	"\x0fproject_members\x18\x02 \x03(\v2 .metalstack.api.v2.ProjectMemberR\x0eprojectMembers\"\xbf\x01\n" +
	"\x1bProjectServiceCreateRequest\x12 \n" +
	"\x05login\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x02\x18\x80\x01R\x05login\x12\x1d\n" +
	"\x04name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x02\x18@R\x04name\x12,\n" +
	"\vdescription\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x02\x18\x80\x04R\vdescription\x12\"\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tH\x00R\tavatarUrl\x88\x01\x01B\r\n" +
	"\v_avatar_url\"T\n" +
	"\x1cProjectServiceCreateResponse\x124\n" +
	"\aproject\x18\x01 \x01(\v2\x1a.metalstack.api.v2.ProjectR\aproject\"A\n" +
	"\x1bProjectServiceDeleteRequest\x12\"\n" +
	"\aproject\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aproject\"T\n" +
	"\x1cProjectServiceDeleteResponse\x124\n" +
	"\aproject\x18\x01 \x01(\v2\x1a.metalstack.api.v2.ProjectR\aproject\"\xe4\x01\n" +
	"\x1bProjectServiceUpdateRequest\x12\"\n" +
	"\aproject\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aproject\x12\"\n" +
	"\x04name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x02\x18@H\x00R\x04name\x88\x01\x01\x121\n" +
	"\vdescription\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x02\x18\x80\x04H\x01R\vdescription\x88\x01\x01\x12\"\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tH\x02R\tavatarUrl\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_avatar_url\"T\n" +
	"\x1cProjectServiceUpdateResponse\x124\n" +
	"\aproject\x18\x01 \x01(\v2\x1a.metalstack.api.v2.ProjectR\aproject\"\x7f\n" +
	"\x1bProjectServiceInviteRequest\x12\"\n" +
	"\aproject\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aproject\x12<\n" +
	"\x04role\x18\x03 \x01(\x0e2\x1e.metalstack.api.v2.ProjectRoleB\b\xbaH\x05\x82\x01\x02\x10\x01R\x04role\"X\n" +
	"\x1cProjectServiceInviteResponse\x128\n" +
	"\x06invite\x18\x01 \x01(\v2 .metalstack.api.v2.ProjectInviteR\x06invite\"F\n" +
	" ProjectServiceInvitesListRequest\x12\"\n" +
	"\aproject\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aproject\"_\n" +
	"!ProjectServiceInvitesListResponse\x12:\n" +
	"\ainvites\x18\x01 \x03(\v2 .metalstack.api.v2.ProjectInviteR\ainvites\"8\n" +
	"\x1eProjectServiceInviteGetRequest\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\"[\n" +
	"\x1fProjectServiceInviteGetResponse\x128\n" +
	"\x06invite\x18\x01 \x01(\v2 .metalstack.api.v2.ProjectInviteR\x06invite\"d\n" +
	"!ProjectServiceRemoveMemberRequest\x12\"\n" +
	"\aproject\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aproject\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\"$\n" +
	"\"ProjectServiceRemoveMemberResponse\"\xa2\x01\n" +
	"!ProjectServiceUpdateMemberRequest\x12\"\n" +
	"\aproject\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aproject\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\x12<\n" +
	"\x04role\x18\x03 \x01(\x0e2\x1e.metalstack.api.v2.ProjectRoleB\b\xbaH\x05\x82\x01\x02\x10\x01R\x04role\"m\n" +
	"\"ProjectServiceUpdateMemberResponse\x12G\n" +
	"\x0eproject_member\x18\x05 \x01(\v2 .metalstack.api.v2.ProjectMemberR\rprojectMember\";\n" +
	"!ProjectServiceInviteAcceptRequest\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\"a\n" +
	"\"ProjectServiceInviteAcceptResponse\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12!\n" +
	"\fproject_name\x18\x02 \x01(\tR\vprojectName\"_\n" +
	"!ProjectServiceInviteDeleteRequest\x12\"\n" +
	"\aproject\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aproject\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\"$\n" +
	"\"ProjectServiceInviteDeleteResponse2\xef\v\n" +
	"\x0eProjectService\x12m\n" +
	"\x04List\x12,.metalstack.api.v2.ProjectServiceListRequest\x1a-.metalstack.api.v2.ProjectServiceListResponse\"\b\xd8\xf3\x18\x03\xe0\xf3\x18\x02\x12m\n" +
	"\x03Get\x12+.metalstack.api.v2.ProjectServiceGetRequest\x1a,.metalstack.api.v2.ProjectServiceGetResponse\"\v\xca\xf3\x18\x03\x01\x02\x03\xe0\xf3\x18\x02\x12u\n" +
	"\x06Create\x12..metalstack.api.v2.ProjectServiceCreateRequest\x1a/.metalstack.api.v2.ProjectServiceCreateResponse\"\n" +
	"\xc2\xf3\x18\x02\x01\x02\xe0\xf3\x18\x01\x12t\n" +
	"\x06Delete\x12..metalstack.api.v2.ProjectServiceDeleteRequest\x1a/.metalstack.api.v2.ProjectServiceDeleteResponse\"\t\xca\xf3\x18\x01\x01\xe0\xf3\x18\x01\x12u\n" +
	"\x06Update\x12..metalstack.api.v2.ProjectServiceUpdateRequest\x1a/.metalstack.api.v2.ProjectServiceUpdateResponse\"\n" +
	"\xca\xf3\x18\x02\x01\x02\xe0\xf3\x18\x01\x12\x86\x01\n" +
	"\fRemoveMember\x124.metalstack.api.v2.ProjectServiceRemoveMemberRequest\x1a5.metalstack.api.v2.ProjectServiceRemoveMemberResponse\"\t\xca\xf3\x18\x01\x01\xe0\xf3\x18\x01\x12\x86\x01\n" +
	"\fUpdateMember\x124.metalstack.api.v2.ProjectServiceUpdateMemberRequest\x1a5.metalstack.api.v2.ProjectServiceUpdateMemberResponse\"\t\xca\xf3\x18\x01\x01\xe0\xf3\x18\x01\x12t\n" +
	"\x06Invite\x12..metalstack.api.v2.ProjectServiceInviteRequest\x1a/.metalstack.api.v2.ProjectServiceInviteResponse\"\t\xca\xf3\x18\x01\x01\xe0\xf3\x18\x01\x12\x85\x01\n" +
	"\fInviteAccept\x124.metalstack.api.v2.ProjectServiceInviteAcceptRequest\x1a5.metalstack.api.v2.ProjectServiceInviteAcceptResponse\"\b\xd8\xf3\x18\x03\xe0\xf3\x18\x01\x12\x86\x01\n" +
	"\fInviteDelete\x124.metalstack.api.v2.ProjectServiceInviteDeleteRequest\x1a5.metalstack.api.v2.ProjectServiceInviteDeleteResponse\"\t\xca\xf3\x18\x01\x01\xe0\xf3\x18\x01\x12\x83\x01\n" +
	"\vInvitesList\x123.metalstack.api.v2.ProjectServiceInvitesListRequest\x1a4.metalstack.api.v2.ProjectServiceInvitesListResponse\"\t\xca\xf3\x18\x01\x01\xe0\xf3\x18\x02\x12|\n" +
	"\tInviteGet\x121.metalstack.api.v2.ProjectServiceInviteGetRequest\x1a2.metalstack.api.v2.ProjectServiceInviteGetResponse\"\b\xd8\xf3\x18\x03\xe0\xf3\x18\x02B\xc2\x01\n" +
	"\x15com.metalstack.api.v2B\fProjectProtoP\x01Z5github.com/metal-stack/api/go/metalstack/api/v2;apiv2\xa2\x02\x03MAX\xaa\x02\x11Metalstack.Api.V2\xca\x02\x11Metalstack\\Api\\V2\xe2\x02\x1dMetalstack\\Api\\V2\\GPBMetadata\xea\x02\x13Metalstack::Api::V2b\x06proto3"

var (
	file_metalstack_api_v2_project_proto_rawDescOnce sync.Once
	file_metalstack_api_v2_project_proto_rawDescData []byte
)

func file_metalstack_api_v2_project_proto_rawDescGZIP() []byte {
	file_metalstack_api_v2_project_proto_rawDescOnce.Do(func() {
		file_metalstack_api_v2_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metalstack_api_v2_project_proto_rawDesc), len(file_metalstack_api_v2_project_proto_rawDesc)))
	})
	return file_metalstack_api_v2_project_proto_rawDescData
}

var file_metalstack_api_v2_project_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_metalstack_api_v2_project_proto_goTypes = []any{
	(*Project)(nil),                            // 0: metalstack.api.v2.Project
	(*ProjectMember)(nil),                      // 1: metalstack.api.v2.ProjectMember
	(*ProjectInvite)(nil),                      // 2: metalstack.api.v2.ProjectInvite
	(*ProjectServiceListRequest)(nil),          // 3: metalstack.api.v2.ProjectServiceListRequest
	(*ProjectServiceListResponse)(nil),         // 4: metalstack.api.v2.ProjectServiceListResponse
	(*ProjectServiceGetRequest)(nil),           // 5: metalstack.api.v2.ProjectServiceGetRequest
	(*ProjectServiceGetResponse)(nil),          // 6: metalstack.api.v2.ProjectServiceGetResponse
	(*ProjectServiceCreateRequest)(nil),        // 7: metalstack.api.v2.ProjectServiceCreateRequest
	(*ProjectServiceCreateResponse)(nil),       // 8: metalstack.api.v2.ProjectServiceCreateResponse
	(*ProjectServiceDeleteRequest)(nil),        // 9: metalstack.api.v2.ProjectServiceDeleteRequest
	(*ProjectServiceDeleteResponse)(nil),       // 10: metalstack.api.v2.ProjectServiceDeleteResponse
	(*ProjectServiceUpdateRequest)(nil),        // 11: metalstack.api.v2.ProjectServiceUpdateRequest
	(*ProjectServiceUpdateResponse)(nil),       // 12: metalstack.api.v2.ProjectServiceUpdateResponse
	(*ProjectServiceInviteRequest)(nil),        // 13: metalstack.api.v2.ProjectServiceInviteRequest
	(*ProjectServiceInviteResponse)(nil),       // 14: metalstack.api.v2.ProjectServiceInviteResponse
	(*ProjectServiceInvitesListRequest)(nil),   // 15: metalstack.api.v2.ProjectServiceInvitesListRequest
	(*ProjectServiceInvitesListResponse)(nil),  // 16: metalstack.api.v2.ProjectServiceInvitesListResponse
	(*ProjectServiceInviteGetRequest)(nil),     // 17: metalstack.api.v2.ProjectServiceInviteGetRequest
	(*ProjectServiceInviteGetResponse)(nil),    // 18: metalstack.api.v2.ProjectServiceInviteGetResponse
	(*ProjectServiceRemoveMemberRequest)(nil),  // 19: metalstack.api.v2.ProjectServiceRemoveMemberRequest
	(*ProjectServiceRemoveMemberResponse)(nil), // 20: metalstack.api.v2.ProjectServiceRemoveMemberResponse
	(*ProjectServiceUpdateMemberRequest)(nil),  // 21: metalstack.api.v2.ProjectServiceUpdateMemberRequest
	(*ProjectServiceUpdateMemberResponse)(nil), // 22: metalstack.api.v2.ProjectServiceUpdateMemberResponse
	(*ProjectServiceInviteAcceptRequest)(nil),  // 23: metalstack.api.v2.ProjectServiceInviteAcceptRequest
	(*ProjectServiceInviteAcceptResponse)(nil), // 24: metalstack.api.v2.ProjectServiceInviteAcceptResponse
	(*ProjectServiceInviteDeleteRequest)(nil),  // 25: metalstack.api.v2.ProjectServiceInviteDeleteRequest
	(*ProjectServiceInviteDeleteResponse)(nil), // 26: metalstack.api.v2.ProjectServiceInviteDeleteResponse
	(*Meta)(nil),                  // 27: metalstack.api.v2.Meta
	(ProjectRole)(0),              // 28: metalstack.api.v2.ProjectRole
	(*timestamppb.Timestamp)(nil), // 29: google.protobuf.Timestamp
}
var file_metalstack_api_v2_project_proto_depIdxs = []int32{
	27, // 0: metalstack.api.v2.Project.meta:type_name -> metalstack.api.v2.Meta
	28, // 1: metalstack.api.v2.ProjectMember.role:type_name -> metalstack.api.v2.ProjectRole
	29, // 2: metalstack.api.v2.ProjectMember.created_at:type_name -> google.protobuf.Timestamp
	28, // 3: metalstack.api.v2.ProjectInvite.role:type_name -> metalstack.api.v2.ProjectRole
	29, // 4: metalstack.api.v2.ProjectInvite.expires_at:type_name -> google.protobuf.Timestamp
	29, // 5: metalstack.api.v2.ProjectInvite.joined_at:type_name -> google.protobuf.Timestamp
	0,  // 6: metalstack.api.v2.ProjectServiceListResponse.projects:type_name -> metalstack.api.v2.Project
	0,  // 7: metalstack.api.v2.ProjectServiceGetResponse.project:type_name -> metalstack.api.v2.Project
	1,  // 8: metalstack.api.v2.ProjectServiceGetResponse.project_members:type_name -> metalstack.api.v2.ProjectMember
	0,  // 9: metalstack.api.v2.ProjectServiceCreateResponse.project:type_name -> metalstack.api.v2.Project
	0,  // 10: metalstack.api.v2.ProjectServiceDeleteResponse.project:type_name -> metalstack.api.v2.Project
	0,  // 11: metalstack.api.v2.ProjectServiceUpdateResponse.project:type_name -> metalstack.api.v2.Project
	28, // 12: metalstack.api.v2.ProjectServiceInviteRequest.role:type_name -> metalstack.api.v2.ProjectRole
	2,  // 13: metalstack.api.v2.ProjectServiceInviteResponse.invite:type_name -> metalstack.api.v2.ProjectInvite
	2,  // 14: metalstack.api.v2.ProjectServiceInvitesListResponse.invites:type_name -> metalstack.api.v2.ProjectInvite
	2,  // 15: metalstack.api.v2.ProjectServiceInviteGetResponse.invite:type_name -> metalstack.api.v2.ProjectInvite
	28, // 16: metalstack.api.v2.ProjectServiceUpdateMemberRequest.role:type_name -> metalstack.api.v2.ProjectRole
	1,  // 17: metalstack.api.v2.ProjectServiceUpdateMemberResponse.project_member:type_name -> metalstack.api.v2.ProjectMember
	3,  // 18: metalstack.api.v2.ProjectService.List:input_type -> metalstack.api.v2.ProjectServiceListRequest
	5,  // 19: metalstack.api.v2.ProjectService.Get:input_type -> metalstack.api.v2.ProjectServiceGetRequest
	7,  // 20: metalstack.api.v2.ProjectService.Create:input_type -> metalstack.api.v2.ProjectServiceCreateRequest
	9,  // 21: metalstack.api.v2.ProjectService.Delete:input_type -> metalstack.api.v2.ProjectServiceDeleteRequest
	11, // 22: metalstack.api.v2.ProjectService.Update:input_type -> metalstack.api.v2.ProjectServiceUpdateRequest
	19, // 23: metalstack.api.v2.ProjectService.RemoveMember:input_type -> metalstack.api.v2.ProjectServiceRemoveMemberRequest
	21, // 24: metalstack.api.v2.ProjectService.UpdateMember:input_type -> metalstack.api.v2.ProjectServiceUpdateMemberRequest
	13, // 25: metalstack.api.v2.ProjectService.Invite:input_type -> metalstack.api.v2.ProjectServiceInviteRequest
	23, // 26: metalstack.api.v2.ProjectService.InviteAccept:input_type -> metalstack.api.v2.ProjectServiceInviteAcceptRequest
	25, // 27: metalstack.api.v2.ProjectService.InviteDelete:input_type -> metalstack.api.v2.ProjectServiceInviteDeleteRequest
	15, // 28: metalstack.api.v2.ProjectService.InvitesList:input_type -> metalstack.api.v2.ProjectServiceInvitesListRequest
	17, // 29: metalstack.api.v2.ProjectService.InviteGet:input_type -> metalstack.api.v2.ProjectServiceInviteGetRequest
	4,  // 30: metalstack.api.v2.ProjectService.List:output_type -> metalstack.api.v2.ProjectServiceListResponse
	6,  // 31: metalstack.api.v2.ProjectService.Get:output_type -> metalstack.api.v2.ProjectServiceGetResponse
	8,  // 32: metalstack.api.v2.ProjectService.Create:output_type -> metalstack.api.v2.ProjectServiceCreateResponse
	10, // 33: metalstack.api.v2.ProjectService.Delete:output_type -> metalstack.api.v2.ProjectServiceDeleteResponse
	12, // 34: metalstack.api.v2.ProjectService.Update:output_type -> metalstack.api.v2.ProjectServiceUpdateResponse
	20, // 35: metalstack.api.v2.ProjectService.RemoveMember:output_type -> metalstack.api.v2.ProjectServiceRemoveMemberResponse
	22, // 36: metalstack.api.v2.ProjectService.UpdateMember:output_type -> metalstack.api.v2.ProjectServiceUpdateMemberResponse
	14, // 37: metalstack.api.v2.ProjectService.Invite:output_type -> metalstack.api.v2.ProjectServiceInviteResponse
	24, // 38: metalstack.api.v2.ProjectService.InviteAccept:output_type -> metalstack.api.v2.ProjectServiceInviteAcceptResponse
	26, // 39: metalstack.api.v2.ProjectService.InviteDelete:output_type -> metalstack.api.v2.ProjectServiceInviteDeleteResponse
	16, // 40: metalstack.api.v2.ProjectService.InvitesList:output_type -> metalstack.api.v2.ProjectServiceInvitesListResponse
	18, // 41: metalstack.api.v2.ProjectService.InviteGet:output_type -> metalstack.api.v2.ProjectServiceInviteGetResponse
	30, // [30:42] is the sub-list for method output_type
	18, // [18:30] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_metalstack_api_v2_project_proto_init() }
func file_metalstack_api_v2_project_proto_init() {
	if File_metalstack_api_v2_project_proto != nil {
		return
	}
	file_metalstack_api_v2_common_proto_init()
	file_metalstack_api_v2_project_proto_msgTypes[0].OneofWrappers = []any{}
	file_metalstack_api_v2_project_proto_msgTypes[3].OneofWrappers = []any{}
	file_metalstack_api_v2_project_proto_msgTypes[7].OneofWrappers = []any{}
	file_metalstack_api_v2_project_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metalstack_api_v2_project_proto_rawDesc), len(file_metalstack_api_v2_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metalstack_api_v2_project_proto_goTypes,
		DependencyIndexes: file_metalstack_api_v2_project_proto_depIdxs,
		MessageInfos:      file_metalstack_api_v2_project_proto_msgTypes,
	}.Build()
	File_metalstack_api_v2_project_proto = out.File
	file_metalstack_api_v2_project_proto_goTypes = nil
	file_metalstack_api_v2_project_proto_depIdxs = nil
}
