// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package infrav2connect

import (
	"context"

	"connectrpc.com/connect"
	"github.com/metal-stack/api/go/metalstack/infra/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewBMCServiceHandler creates a new instance of BMCServiceHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBMCServiceHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *BMCServiceHandler {
	mock := &BMCServiceHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BMCServiceHandler is an autogenerated mock type for the BMCServiceHandler type
type BMCServiceHandler struct {
	mock.Mock
}

type BMCServiceHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *BMCServiceHandler) EXPECT() *BMCServiceHandler_Expecter {
	return &BMCServiceHandler_Expecter{mock: &_m.Mock}
}

// UpdateBMCInfo provides a mock function for the type BMCServiceHandler
func (_mock *BMCServiceHandler) UpdateBMCInfo(context1 context.Context, updateBMCInfoRequest *infrav2.UpdateBMCInfoRequest) (*infrav2.UpdateBMCInfoResponse, error) {
	ret := _mock.Called(context1, updateBMCInfoRequest)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBMCInfo")
	}

	var r0 *infrav2.UpdateBMCInfoResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *infrav2.UpdateBMCInfoRequest) (*infrav2.UpdateBMCInfoResponse, error)); ok {
		return returnFunc(context1, updateBMCInfoRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *infrav2.UpdateBMCInfoRequest) *infrav2.UpdateBMCInfoResponse); ok {
		r0 = returnFunc(context1, updateBMCInfoRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*infrav2.UpdateBMCInfoResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *infrav2.UpdateBMCInfoRequest) error); ok {
		r1 = returnFunc(context1, updateBMCInfoRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BMCServiceHandler_UpdateBMCInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBMCInfo'
type BMCServiceHandler_UpdateBMCInfo_Call struct {
	*mock.Call
}

// UpdateBMCInfo is a helper method to define mock.On call
//   - context1 context.Context
//   - updateBMCInfoRequest *infrav2.UpdateBMCInfoRequest
func (_e *BMCServiceHandler_Expecter) UpdateBMCInfo(context1 interface{}, updateBMCInfoRequest interface{}) *BMCServiceHandler_UpdateBMCInfo_Call {
	return &BMCServiceHandler_UpdateBMCInfo_Call{Call: _e.mock.On("UpdateBMCInfo", context1, updateBMCInfoRequest)}
}

func (_c *BMCServiceHandler_UpdateBMCInfo_Call) Run(run func(context1 context.Context, updateBMCInfoRequest *infrav2.UpdateBMCInfoRequest)) *BMCServiceHandler_UpdateBMCInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *infrav2.UpdateBMCInfoRequest
		if args[1] != nil {
			arg1 = args[1].(*infrav2.UpdateBMCInfoRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BMCServiceHandler_UpdateBMCInfo_Call) Return(updateBMCInfoResponse *infrav2.UpdateBMCInfoResponse, err error) *BMCServiceHandler_UpdateBMCInfo_Call {
	_c.Call.Return(updateBMCInfoResponse, err)
	return _c
}

func (_c *BMCServiceHandler_UpdateBMCInfo_Call) RunAndReturn(run func(context1 context.Context, updateBMCInfoRequest *infrav2.UpdateBMCInfoRequest) (*infrav2.UpdateBMCInfoResponse, error)) *BMCServiceHandler_UpdateBMCInfo_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForMachineEvent provides a mock function for the type BMCServiceHandler
func (_mock *BMCServiceHandler) WaitForMachineEvent(context1 context.Context, waitForMachineEventRequest *infrav2.WaitForMachineEventRequest, serverStream *connect.ServerStream[infrav2.WaitForMachineEventResponse]) error {
	ret := _mock.Called(context1, waitForMachineEventRequest, serverStream)

	if len(ret) == 0 {
		panic("no return value specified for WaitForMachineEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *infrav2.WaitForMachineEventRequest, *connect.ServerStream[infrav2.WaitForMachineEventResponse]) error); ok {
		r0 = returnFunc(context1, waitForMachineEventRequest, serverStream)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// BMCServiceHandler_WaitForMachineEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForMachineEvent'
type BMCServiceHandler_WaitForMachineEvent_Call struct {
	*mock.Call
}

// WaitForMachineEvent is a helper method to define mock.On call
//   - context1 context.Context
//   - waitForMachineEventRequest *infrav2.WaitForMachineEventRequest
//   - serverStream *connect.ServerStream[infrav2.WaitForMachineEventResponse]
func (_e *BMCServiceHandler_Expecter) WaitForMachineEvent(context1 interface{}, waitForMachineEventRequest interface{}, serverStream interface{}) *BMCServiceHandler_WaitForMachineEvent_Call {
	return &BMCServiceHandler_WaitForMachineEvent_Call{Call: _e.mock.On("WaitForMachineEvent", context1, waitForMachineEventRequest, serverStream)}
}

func (_c *BMCServiceHandler_WaitForMachineEvent_Call) Run(run func(context1 context.Context, waitForMachineEventRequest *infrav2.WaitForMachineEventRequest, serverStream *connect.ServerStream[infrav2.WaitForMachineEventResponse])) *BMCServiceHandler_WaitForMachineEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *infrav2.WaitForMachineEventRequest
		if args[1] != nil {
			arg1 = args[1].(*infrav2.WaitForMachineEventRequest)
		}
		var arg2 *connect.ServerStream[infrav2.WaitForMachineEventResponse]
		if args[2] != nil {
			arg2 = args[2].(*connect.ServerStream[infrav2.WaitForMachineEventResponse])
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *BMCServiceHandler_WaitForMachineEvent_Call) Return(err error) *BMCServiceHandler_WaitForMachineEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *BMCServiceHandler_WaitForMachineEvent_Call) RunAndReturn(run func(context1 context.Context, waitForMachineEventRequest *infrav2.WaitForMachineEventRequest, serverStream *connect.ServerStream[infrav2.WaitForMachineEventResponse]) error) *BMCServiceHandler_WaitForMachineEvent_Call {
	_c.Call.Return(run)
	return _c
}
