syntax = "proto3";

package metalstack.cli.v2;

import "buf/validate/validate.proto";
import "metalstack/api/v2/predefined_rules.proto";
import "metalstack/api/v2/tenant.proto";

// TenantMember defines a user that participates in a tenant.
message TenantMember {
  // tenant is the login tenant to which the member belongs.
  string tenant = 1 [(buf.validate.field).string.(metalstack.api.v2.is_tenant_login) = true];
  // TenantMember is the tenant member.
  metalstack.api.v2.TenantMember tenant_member = 2;
}
