// Code generated by mockery v2.53.4. DO NOT EDIT.

package validate

import mock "github.com/stretchr/testify/mock"

// isFixed64Rules_LessThan is an autogenerated mock type for the isFixed64Rules_LessThan type
type isFixed64Rules_LessThan struct {
	mock.Mock
}

// isFixed64Rules_LessThan provides a mock function with no fields
func (_m *isFixed64Rules_LessThan) isFixed64Rules_LessThan() {
	_m.Called()
}

// newIsFixed64Rules_LessThan creates a new instance of isFixed64Rules_LessThan. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newIsFixed64Rules_LessThan(t interface {
	mock.TestingT
	Cleanup(func())
}) *isFixed64Rules_LessThan {
	mock := &isFixed64Rules_LessThan{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
