# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: metalstack/admin/v2/project.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import metalstack.admin.v2.project_pb2 as metalstack_dot_admin_dot_v2_dot_project__pb2


class ProjectService(Protocol):
    async def create(self, request: metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceCreateRequest, ctx: RequestContext) -> metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceCreateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list(self, request: metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceListRequest, ctx: RequestContext) -> metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceListResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def add_member(self, request: metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceAddMemberRequest, ctx: RequestContext) -> metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceAddMemberResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def remove_member(self, request: metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceRemoveMemberRequest, ctx: RequestContext) -> metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceRemoveMemberResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ProjectServiceASGIApplication(ConnectASGIApplication[ProjectService]):
    def __init__(self, service: ProjectService | AsyncGenerator[ProjectService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/metalstack.admin.v2.ProjectService/Create": Endpoint.unary(
                    method=MethodInfo(
                        name="Create",
                        service_name="metalstack.admin.v2.ProjectService",
                        input=metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceCreateRequest,
                        output=metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceCreateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create,
                ),
                "/metalstack.admin.v2.ProjectService/List": Endpoint.unary(
                    method=MethodInfo(
                        name="List",
                        service_name="metalstack.admin.v2.ProjectService",
                        input=metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceListRequest,
                        output=metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceListResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list,
                ),
                "/metalstack.admin.v2.ProjectService/AddMember": Endpoint.unary(
                    method=MethodInfo(
                        name="AddMember",
                        service_name="metalstack.admin.v2.ProjectService",
                        input=metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceAddMemberRequest,
                        output=metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceAddMemberResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.add_member,
                ),
                "/metalstack.admin.v2.ProjectService/RemoveMember": Endpoint.unary(
                    method=MethodInfo(
                        name="RemoveMember",
                        service_name="metalstack.admin.v2.ProjectService",
                        input=metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceRemoveMemberRequest,
                        output=metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceRemoveMemberResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.remove_member,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/metalstack.admin.v2.ProjectService"


class ProjectServiceClient(ConnectClient):
    async def create(
        self,
        request: metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceCreateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceCreateResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Create",
                service_name="metalstack.admin.v2.ProjectService",
                input=metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceCreateRequest,
                output=metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceCreateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list(
        self,
        request: metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceListRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceListResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="List",
                service_name="metalstack.admin.v2.ProjectService",
                input=metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceListRequest,
                output=metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceListResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def add_member(
        self,
        request: metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceAddMemberRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceAddMemberResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AddMember",
                service_name="metalstack.admin.v2.ProjectService",
                input=metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceAddMemberRequest,
                output=metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceAddMemberResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def remove_member(
        self,
        request: metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceRemoveMemberRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceRemoveMemberResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RemoveMember",
                service_name="metalstack.admin.v2.ProjectService",
                input=metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceRemoveMemberRequest,
                output=metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceRemoveMemberResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class ProjectServiceSync(Protocol):
    def create(self, request: metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceCreateRequest, ctx: RequestContext) -> metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceCreateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list(self, request: metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceListRequest, ctx: RequestContext) -> metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceListResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def add_member(self, request: metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceAddMemberRequest, ctx: RequestContext) -> metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceAddMemberResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def remove_member(self, request: metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceRemoveMemberRequest, ctx: RequestContext) -> metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceRemoveMemberResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ProjectServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: ProjectServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/metalstack.admin.v2.ProjectService/Create": EndpointSync.unary(
                    method=MethodInfo(
                        name="Create",
                        service_name="metalstack.admin.v2.ProjectService",
                        input=metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceCreateRequest,
                        output=metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceCreateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create,
                ),
                "/metalstack.admin.v2.ProjectService/List": EndpointSync.unary(
                    method=MethodInfo(
                        name="List",
                        service_name="metalstack.admin.v2.ProjectService",
                        input=metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceListRequest,
                        output=metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceListResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list,
                ),
                "/metalstack.admin.v2.ProjectService/AddMember": EndpointSync.unary(
                    method=MethodInfo(
                        name="AddMember",
                        service_name="metalstack.admin.v2.ProjectService",
                        input=metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceAddMemberRequest,
                        output=metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceAddMemberResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.add_member,
                ),
                "/metalstack.admin.v2.ProjectService/RemoveMember": EndpointSync.unary(
                    method=MethodInfo(
                        name="RemoveMember",
                        service_name="metalstack.admin.v2.ProjectService",
                        input=metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceRemoveMemberRequest,
                        output=metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceRemoveMemberResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.remove_member,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/metalstack.admin.v2.ProjectService"


class ProjectServiceClientSync(ConnectClientSync):
    def create(
        self,
        request: metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceCreateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceCreateResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Create",
                service_name="metalstack.admin.v2.ProjectService",
                input=metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceCreateRequest,
                output=metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceCreateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list(
        self,
        request: metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceListRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceListResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="List",
                service_name="metalstack.admin.v2.ProjectService",
                input=metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceListRequest,
                output=metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceListResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def add_member(
        self,
        request: metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceAddMemberRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceAddMemberResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AddMember",
                service_name="metalstack.admin.v2.ProjectService",
                input=metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceAddMemberRequest,
                output=metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceAddMemberResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def remove_member(
        self,
        request: metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceRemoveMemberRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceRemoveMemberResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RemoveMember",
                service_name="metalstack.admin.v2.ProjectService",
                input=metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceRemoveMemberRequest,
                output=metalstack_dot_admin_dot_v2_dot_project__pb2.ProjectServiceRemoveMemberResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


