# Generated from metalstack/admin/v2/task.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.11.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync

from .task_pb import TaskServiceDeleteRequest, TaskServiceDeleteResponse, TaskServiceGetRequest, TaskServiceGetResponse, TaskServiceListRequest, TaskServiceListResponse, TaskServiceQueuesRequest, TaskServiceQueuesResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext


class TaskService(Protocol):
    async def get(self, request: TaskServiceGetRequest, ctx: RequestContext[TaskServiceGetRequest, TaskServiceGetResponse]) -> TaskServiceGetResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def delete(self, request: TaskServiceDeleteRequest, ctx: RequestContext[TaskServiceDeleteRequest, TaskServiceDeleteResponse]) -> TaskServiceDeleteResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def queues(self, request: TaskServiceQueuesRequest, ctx: RequestContext[TaskServiceQueuesRequest, TaskServiceQueuesResponse]) -> TaskServiceQueuesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list(self, request: TaskServiceListRequest, ctx: RequestContext[TaskServiceListRequest, TaskServiceListResponse]) -> TaskServiceListResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class TaskServiceASGIApplication(ConnectASGIApplication[TaskService]):
    def __init__(
        self,
        service: TaskService | AsyncGenerator[TaskService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/metalstack.admin.v2.TaskService/Get": Endpoint.unary(
                    method=MethodInfo(
                        name="Get",
                        service_name="metalstack.admin.v2.TaskService",
                        input=TaskServiceGetRequest,
                        output=TaskServiceGetResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get,
                ),
                "/metalstack.admin.v2.TaskService/Delete": Endpoint.unary(
                    method=MethodInfo(
                        name="Delete",
                        service_name="metalstack.admin.v2.TaskService",
                        input=TaskServiceDeleteRequest,
                        output=TaskServiceDeleteResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete,
                ),
                "/metalstack.admin.v2.TaskService/Queues": Endpoint.unary(
                    method=MethodInfo(
                        name="Queues",
                        service_name="metalstack.admin.v2.TaskService",
                        input=TaskServiceQueuesRequest,
                        output=TaskServiceQueuesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.queues,
                ),
                "/metalstack.admin.v2.TaskService/List": Endpoint.unary(
                    method=MethodInfo(
                        name="List",
                        service_name="metalstack.admin.v2.TaskService",
                        input=TaskServiceListRequest,
                        output=TaskServiceListResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/metalstack.admin.v2.TaskService"


class TaskServiceClient(ConnectClient):
    async def get(
        self,
        request: TaskServiceGetRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> TaskServiceGetResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Get",
                service_name="metalstack.admin.v2.TaskService",
                input=TaskServiceGetRequest,
                output=TaskServiceGetResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete(
        self,
        request: TaskServiceDeleteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> TaskServiceDeleteResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Delete",
                service_name="metalstack.admin.v2.TaskService",
                input=TaskServiceDeleteRequest,
                output=TaskServiceDeleteResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def queues(
        self,
        request: TaskServiceQueuesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> TaskServiceQueuesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Queues",
                service_name="metalstack.admin.v2.TaskService",
                input=TaskServiceQueuesRequest,
                output=TaskServiceQueuesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list(
        self,
        request: TaskServiceListRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> TaskServiceListResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="List",
                service_name="metalstack.admin.v2.TaskService",
                input=TaskServiceListRequest,
                output=TaskServiceListResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class TaskServiceSync(Protocol):
    def get(self, request: TaskServiceGetRequest, ctx: RequestContext[TaskServiceGetRequest, TaskServiceGetResponse]) -> TaskServiceGetResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def delete(self, request: TaskServiceDeleteRequest, ctx: RequestContext[TaskServiceDeleteRequest, TaskServiceDeleteResponse]) -> TaskServiceDeleteResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def queues(self, request: TaskServiceQueuesRequest, ctx: RequestContext[TaskServiceQueuesRequest, TaskServiceQueuesResponse]) -> TaskServiceQueuesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list(self, request: TaskServiceListRequest, ctx: RequestContext[TaskServiceListRequest, TaskServiceListResponse]) -> TaskServiceListResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class TaskServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: TaskServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/metalstack.admin.v2.TaskService/Get": EndpointSync.unary(
                    method=MethodInfo(
                        name="Get",
                        service_name="metalstack.admin.v2.TaskService",
                        input=TaskServiceGetRequest,
                        output=TaskServiceGetResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get,
                ),
                "/metalstack.admin.v2.TaskService/Delete": EndpointSync.unary(
                    method=MethodInfo(
                        name="Delete",
                        service_name="metalstack.admin.v2.TaskService",
                        input=TaskServiceDeleteRequest,
                        output=TaskServiceDeleteResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete,
                ),
                "/metalstack.admin.v2.TaskService/Queues": EndpointSync.unary(
                    method=MethodInfo(
                        name="Queues",
                        service_name="metalstack.admin.v2.TaskService",
                        input=TaskServiceQueuesRequest,
                        output=TaskServiceQueuesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.queues,
                ),
                "/metalstack.admin.v2.TaskService/List": EndpointSync.unary(
                    method=MethodInfo(
                        name="List",
                        service_name="metalstack.admin.v2.TaskService",
                        input=TaskServiceListRequest,
                        output=TaskServiceListResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/metalstack.admin.v2.TaskService"


class TaskServiceClientSync(ConnectClientSync):
    def get(
        self,
        request: TaskServiceGetRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> TaskServiceGetResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Get",
                service_name="metalstack.admin.v2.TaskService",
                input=TaskServiceGetRequest,
                output=TaskServiceGetResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def delete(
        self,
        request: TaskServiceDeleteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> TaskServiceDeleteResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Delete",
                service_name="metalstack.admin.v2.TaskService",
                input=TaskServiceDeleteRequest,
                output=TaskServiceDeleteResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def queues(
        self,
        request: TaskServiceQueuesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> TaskServiceQueuesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Queues",
                service_name="metalstack.admin.v2.TaskService",
                input=TaskServiceQueuesRequest,
                output=TaskServiceQueuesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list(
        self,
        request: TaskServiceListRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> TaskServiceListResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="List",
                service_name="metalstack.admin.v2.TaskService",
                input=TaskServiceListRequest,
                output=TaskServiceListResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
