# Generated from metalstack/infra/v2/component.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.11.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync

from .component_pb import ComponentServicePingRequest, ComponentServicePingResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext


class ComponentService(Protocol):
    async def ping(self, request: ComponentServicePingRequest, ctx: RequestContext[ComponentServicePingRequest, ComponentServicePingResponse]) -> ComponentServicePingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class ComponentServiceASGIApplication(ConnectASGIApplication[ComponentService]):
    def __init__(
        self,
        service: ComponentService | AsyncGenerator[ComponentService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/metalstack.infra.v2.ComponentService/Ping": Endpoint.unary(
                    method=MethodInfo(
                        name="Ping",
                        service_name="metalstack.infra.v2.ComponentService",
                        input=ComponentServicePingRequest,
                        output=ComponentServicePingResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.ping,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/metalstack.infra.v2.ComponentService"


class ComponentServiceClient(ConnectClient):
    async def ping(
        self,
        request: ComponentServicePingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ComponentServicePingResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Ping",
                service_name="metalstack.infra.v2.ComponentService",
                input=ComponentServicePingRequest,
                output=ComponentServicePingResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class ComponentServiceSync(Protocol):
    def ping(self, request: ComponentServicePingRequest, ctx: RequestContext[ComponentServicePingRequest, ComponentServicePingResponse]) -> ComponentServicePingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class ComponentServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: ComponentServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/metalstack.infra.v2.ComponentService/Ping": EndpointSync.unary(
                    method=MethodInfo(
                        name="Ping",
                        service_name="metalstack.infra.v2.ComponentService",
                        input=ComponentServicePingRequest,
                        output=ComponentServicePingResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.ping,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/metalstack.infra.v2.ComponentService"


class ComponentServiceClientSync(ConnectClientSync):
    def ping(
        self,
        request: ComponentServicePingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ComponentServicePingResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Ping",
                service_name="metalstack.infra.v2.ComponentService",
                input=ComponentServicePingRequest,
                output=ComponentServicePingResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
