// Code generated by mockery v2.53.0. DO NOT EDIT.

package client

import (
	infrav2connect "github.com/metal-stack/api/go/metalstack/infra/v2/infrav2connect"
	mock "github.com/stretchr/testify/mock"
)

// Infrav2 is an autogenerated mock type for the Infrav2 type
type Infrav2 struct {
	mock.Mock
}

// BMC provides a mock function with no fields
func (_m *Infrav2) BMC() infrav2connect.BMCServiceClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BMC")
	}

	var r0 infrav2connect.BMCServiceClient
	if rf, ok := ret.Get(0).(func() infrav2connect.BMCServiceClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(infrav2connect.BMCServiceClient)
		}
	}

	return r0
}

// NewInfrav2 creates a new instance of Infrav2. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInfrav2(t interface {
	mock.TestingT
	Cleanup(func())
}) *Infrav2 {
	mock := &Infrav2{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
