// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/metal-stack/api/go/metalstack/admin/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewMachineServiceClient creates a new instance of MachineServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMachineServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MachineServiceClient {
	mock := &MachineServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MachineServiceClient is an autogenerated mock type for the MachineServiceClient type
type MachineServiceClient struct {
	mock.Mock
}

type MachineServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MachineServiceClient) EXPECT() *MachineServiceClient_Expecter {
	return &MachineServiceClient_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MachineServiceClient
func (_mock *MachineServiceClient) Get(context1 context.Context, machineServiceGetRequest *adminv2.MachineServiceGetRequest) (*adminv2.MachineServiceGetResponse, error) {
	ret := _mock.Called(context1, machineServiceGetRequest)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *adminv2.MachineServiceGetResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *adminv2.MachineServiceGetRequest) (*adminv2.MachineServiceGetResponse, error)); ok {
		return returnFunc(context1, machineServiceGetRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *adminv2.MachineServiceGetRequest) *adminv2.MachineServiceGetResponse); ok {
		r0 = returnFunc(context1, machineServiceGetRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adminv2.MachineServiceGetResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *adminv2.MachineServiceGetRequest) error); ok {
		r1 = returnFunc(context1, machineServiceGetRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MachineServiceClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MachineServiceClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - machineServiceGetRequest *adminv2.MachineServiceGetRequest
func (_e *MachineServiceClient_Expecter) Get(context1 interface{}, machineServiceGetRequest interface{}) *MachineServiceClient_Get_Call {
	return &MachineServiceClient_Get_Call{Call: _e.mock.On("Get", context1, machineServiceGetRequest)}
}

func (_c *MachineServiceClient_Get_Call) Run(run func(context1 context.Context, machineServiceGetRequest *adminv2.MachineServiceGetRequest)) *MachineServiceClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *adminv2.MachineServiceGetRequest
		if args[1] != nil {
			arg1 = args[1].(*adminv2.MachineServiceGetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MachineServiceClient_Get_Call) Return(machineServiceGetResponse *adminv2.MachineServiceGetResponse, err error) *MachineServiceClient_Get_Call {
	_c.Call.Return(machineServiceGetResponse, err)
	return _c
}

func (_c *MachineServiceClient_Get_Call) RunAndReturn(run func(context1 context.Context, machineServiceGetRequest *adminv2.MachineServiceGetRequest) (*adminv2.MachineServiceGetResponse, error)) *MachineServiceClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MachineServiceClient
func (_mock *MachineServiceClient) List(context1 context.Context, machineServiceListRequest *adminv2.MachineServiceListRequest) (*adminv2.MachineServiceListResponse, error) {
	ret := _mock.Called(context1, machineServiceListRequest)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *adminv2.MachineServiceListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *adminv2.MachineServiceListRequest) (*adminv2.MachineServiceListResponse, error)); ok {
		return returnFunc(context1, machineServiceListRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *adminv2.MachineServiceListRequest) *adminv2.MachineServiceListResponse); ok {
		r0 = returnFunc(context1, machineServiceListRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adminv2.MachineServiceListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *adminv2.MachineServiceListRequest) error); ok {
		r1 = returnFunc(context1, machineServiceListRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MachineServiceClient_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MachineServiceClient_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - machineServiceListRequest *adminv2.MachineServiceListRequest
func (_e *MachineServiceClient_Expecter) List(context1 interface{}, machineServiceListRequest interface{}) *MachineServiceClient_List_Call {
	return &MachineServiceClient_List_Call{Call: _e.mock.On("List", context1, machineServiceListRequest)}
}

func (_c *MachineServiceClient_List_Call) Run(run func(context1 context.Context, machineServiceListRequest *adminv2.MachineServiceListRequest)) *MachineServiceClient_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *adminv2.MachineServiceListRequest
		if args[1] != nil {
			arg1 = args[1].(*adminv2.MachineServiceListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MachineServiceClient_List_Call) Return(machineServiceListResponse *adminv2.MachineServiceListResponse, err error) *MachineServiceClient_List_Call {
	_c.Call.Return(machineServiceListResponse, err)
	return _c
}

func (_c *MachineServiceClient_List_Call) RunAndReturn(run func(context1 context.Context, machineServiceListRequest *adminv2.MachineServiceListRequest) (*adminv2.MachineServiceListResponse, error)) *MachineServiceClient_List_Call {
	_c.Call.Return(run)
	return _c
}
