// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file metalstack/infra/v2/event.proto (package metalstack.infra.v2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_metalstack_api_v2_common } from "../../api/v2/common_pb";
import type { MachineProvisioningEvent } from "../../api/v2/machine_pb";
import { file_metalstack_api_v2_machine } from "../../api/v2/machine_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file metalstack/infra/v2/event.proto.
 */
export const file_metalstack_infra_v2_event: GenFile = /*@__PURE__*/
  fileDesc("Ch9tZXRhbHN0YWNrL2luZnJhL3YyL2V2ZW50LnByb3RvEhNtZXRhbHN0YWNrLmluZnJhLnYyIr8BChdFdmVudFNlcnZpY2VTZW5kUmVxdWVzdBJICgZldmVudHMYASADKAsyOC5tZXRhbHN0YWNrLmluZnJhLnYyLkV2ZW50U2VydmljZVNlbmRSZXF1ZXN0LkV2ZW50c0VudHJ5GloKC0V2ZW50c0VudHJ5EgsKA2tleRgBIAEoCRI6CgV2YWx1ZRgCIAEoCzIrLm1ldGFsc3RhY2suYXBpLnYyLk1hY2hpbmVQcm92aXNpb25pbmdFdmVudDoCOAEiOgoYRXZlbnRTZXJ2aWNlU2VuZFJlc3BvbnNlEg4KBmV2ZW50cxgBIAEoBBIOCgZmYWlsZWQYAiADKAkyfgoMRXZlbnRTZXJ2aWNlEm4KBFNlbmQSLC5tZXRhbHN0YWNrLmluZnJhLnYyLkV2ZW50U2VydmljZVNlbmRSZXF1ZXN0Gi0ubWV0YWxzdGFjay5pbmZyYS52Mi5FdmVudFNlcnZpY2VTZW5kUmVzcG9uc2UiCeDzGALq8xgBAULOAQoXY29tLm1ldGFsc3RhY2suaW5mcmEudjJCCkV2ZW50UHJvdG9QAVo5Z2l0aHViLmNvbS9tZXRhbC1zdGFjay9hcGkvZ28vbWV0YWxzdGFjay9pbmZyYS92MjtpbmZyYXYyogIDTUlYqgITTWV0YWxzdGFjay5JbmZyYS5WMsoCE01ldGFsc3RhY2tcSW5mcmFcVjLiAh9NZXRhbHN0YWNrXEluZnJhXFYyXEdQQk1ldGFkYXRh6gIVTWV0YWxzdGFjazo6SW5mcmE6OlYyYgZwcm90bzM", [file_buf_validate_validate, file_google_protobuf_timestamp, file_metalstack_api_v2_common, file_metalstack_api_v2_machine]);

/**
 * EventServiceSendRequest is the request payload for sending provisioning events.
 *
 * @generated from message metalstack.infra.v2.EventServiceSendRequest
 */
export type EventServiceSendRequest = Message<"metalstack.infra.v2.EventServiceSendRequest"> & {
  /**
   * Events grouped by machine IDs
   *
   * @generated from field: map<string, metalstack.api.v2.MachineProvisioningEvent> events = 1;
   */
  events: { [key: string]: MachineProvisioningEvent };
};

/**
 * Describes the message metalstack.infra.v2.EventServiceSendRequest.
 * Use `create(EventServiceSendRequestSchema)` to create a new message.
 */
export const EventServiceSendRequestSchema: GenMessage<EventServiceSendRequest> = /*@__PURE__*/
  messageDesc(file_metalstack_infra_v2_event, 0);

/**
 * EventServiceSendResponse is the response payload for sending provisioning events.
 *
 * @generated from message metalstack.infra.v2.EventServiceSendResponse
 */
export type EventServiceSendResponse = Message<"metalstack.infra.v2.EventServiceSendResponse"> & {
  /**
   * Events counts the number of events successfully stored in the database
   *
   * @generated from field: uint64 events = 1;
   */
  events: bigint;

  /**
   * Failed contains IDs of all machines whose events could not be stored in the database
   *
   * @generated from field: repeated string failed = 2;
   */
  failed: string[];
};

/**
 * Describes the message metalstack.infra.v2.EventServiceSendResponse.
 * Use `create(EventServiceSendResponseSchema)` to create a new message.
 */
export const EventServiceSendResponseSchema: GenMessage<EventServiceSendResponse> = /*@__PURE__*/
  messageDesc(file_metalstack_infra_v2_event, 1);

/**
 * EventService provides machine provisioning event logging operations.
 *
 * @generated from service metalstack.infra.v2.EventService
 */
export const EventService: GenService<{
  /**
   * Sends a series of machine provisioning events.
   *
   * @generated from rpc metalstack.infra.v2.EventService.Send
   */
  send: {
    methodKind: "unary";
    input: typeof EventServiceSendRequestSchema;
    output: typeof EventServiceSendResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_metalstack_infra_v2_event, 0);

