// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package apiv2connect

import (
	"context"

	"github.com/metal-stack/api/go/metalstack/api/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewIPServiceClient creates a new instance of IPServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPServiceClient {
	mock := &IPServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IPServiceClient is an autogenerated mock type for the IPServiceClient type
type IPServiceClient struct {
	mock.Mock
}

type IPServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *IPServiceClient) EXPECT() *IPServiceClient_Expecter {
	return &IPServiceClient_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type IPServiceClient
func (_mock *IPServiceClient) Create(context1 context.Context, iPServiceCreateRequest *apiv2.IPServiceCreateRequest) (*apiv2.IPServiceCreateResponse, error) {
	ret := _mock.Called(context1, iPServiceCreateRequest)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *apiv2.IPServiceCreateResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv2.IPServiceCreateRequest) (*apiv2.IPServiceCreateResponse, error)); ok {
		return returnFunc(context1, iPServiceCreateRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv2.IPServiceCreateRequest) *apiv2.IPServiceCreateResponse); ok {
		r0 = returnFunc(context1, iPServiceCreateRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv2.IPServiceCreateResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv2.IPServiceCreateRequest) error); ok {
		r1 = returnFunc(context1, iPServiceCreateRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IPServiceClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type IPServiceClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - iPServiceCreateRequest *apiv2.IPServiceCreateRequest
func (_e *IPServiceClient_Expecter) Create(context1 interface{}, iPServiceCreateRequest interface{}) *IPServiceClient_Create_Call {
	return &IPServiceClient_Create_Call{Call: _e.mock.On("Create", context1, iPServiceCreateRequest)}
}

func (_c *IPServiceClient_Create_Call) Run(run func(context1 context.Context, iPServiceCreateRequest *apiv2.IPServiceCreateRequest)) *IPServiceClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv2.IPServiceCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv2.IPServiceCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IPServiceClient_Create_Call) Return(iPServiceCreateResponse *apiv2.IPServiceCreateResponse, err error) *IPServiceClient_Create_Call {
	_c.Call.Return(iPServiceCreateResponse, err)
	return _c
}

func (_c *IPServiceClient_Create_Call) RunAndReturn(run func(context1 context.Context, iPServiceCreateRequest *apiv2.IPServiceCreateRequest) (*apiv2.IPServiceCreateResponse, error)) *IPServiceClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type IPServiceClient
func (_mock *IPServiceClient) Delete(context1 context.Context, iPServiceDeleteRequest *apiv2.IPServiceDeleteRequest) (*apiv2.IPServiceDeleteResponse, error) {
	ret := _mock.Called(context1, iPServiceDeleteRequest)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *apiv2.IPServiceDeleteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv2.IPServiceDeleteRequest) (*apiv2.IPServiceDeleteResponse, error)); ok {
		return returnFunc(context1, iPServiceDeleteRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv2.IPServiceDeleteRequest) *apiv2.IPServiceDeleteResponse); ok {
		r0 = returnFunc(context1, iPServiceDeleteRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv2.IPServiceDeleteResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv2.IPServiceDeleteRequest) error); ok {
		r1 = returnFunc(context1, iPServiceDeleteRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IPServiceClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type IPServiceClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - iPServiceDeleteRequest *apiv2.IPServiceDeleteRequest
func (_e *IPServiceClient_Expecter) Delete(context1 interface{}, iPServiceDeleteRequest interface{}) *IPServiceClient_Delete_Call {
	return &IPServiceClient_Delete_Call{Call: _e.mock.On("Delete", context1, iPServiceDeleteRequest)}
}

func (_c *IPServiceClient_Delete_Call) Run(run func(context1 context.Context, iPServiceDeleteRequest *apiv2.IPServiceDeleteRequest)) *IPServiceClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv2.IPServiceDeleteRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv2.IPServiceDeleteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IPServiceClient_Delete_Call) Return(iPServiceDeleteResponse *apiv2.IPServiceDeleteResponse, err error) *IPServiceClient_Delete_Call {
	_c.Call.Return(iPServiceDeleteResponse, err)
	return _c
}

func (_c *IPServiceClient_Delete_Call) RunAndReturn(run func(context1 context.Context, iPServiceDeleteRequest *apiv2.IPServiceDeleteRequest) (*apiv2.IPServiceDeleteResponse, error)) *IPServiceClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type IPServiceClient
func (_mock *IPServiceClient) Get(context1 context.Context, iPServiceGetRequest *apiv2.IPServiceGetRequest) (*apiv2.IPServiceGetResponse, error) {
	ret := _mock.Called(context1, iPServiceGetRequest)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *apiv2.IPServiceGetResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv2.IPServiceGetRequest) (*apiv2.IPServiceGetResponse, error)); ok {
		return returnFunc(context1, iPServiceGetRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv2.IPServiceGetRequest) *apiv2.IPServiceGetResponse); ok {
		r0 = returnFunc(context1, iPServiceGetRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv2.IPServiceGetResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv2.IPServiceGetRequest) error); ok {
		r1 = returnFunc(context1, iPServiceGetRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IPServiceClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type IPServiceClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - iPServiceGetRequest *apiv2.IPServiceGetRequest
func (_e *IPServiceClient_Expecter) Get(context1 interface{}, iPServiceGetRequest interface{}) *IPServiceClient_Get_Call {
	return &IPServiceClient_Get_Call{Call: _e.mock.On("Get", context1, iPServiceGetRequest)}
}

func (_c *IPServiceClient_Get_Call) Run(run func(context1 context.Context, iPServiceGetRequest *apiv2.IPServiceGetRequest)) *IPServiceClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv2.IPServiceGetRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv2.IPServiceGetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IPServiceClient_Get_Call) Return(iPServiceGetResponse *apiv2.IPServiceGetResponse, err error) *IPServiceClient_Get_Call {
	_c.Call.Return(iPServiceGetResponse, err)
	return _c
}

func (_c *IPServiceClient_Get_Call) RunAndReturn(run func(context1 context.Context, iPServiceGetRequest *apiv2.IPServiceGetRequest) (*apiv2.IPServiceGetResponse, error)) *IPServiceClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type IPServiceClient
func (_mock *IPServiceClient) List(context1 context.Context, iPServiceListRequest *apiv2.IPServiceListRequest) (*apiv2.IPServiceListResponse, error) {
	ret := _mock.Called(context1, iPServiceListRequest)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *apiv2.IPServiceListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv2.IPServiceListRequest) (*apiv2.IPServiceListResponse, error)); ok {
		return returnFunc(context1, iPServiceListRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv2.IPServiceListRequest) *apiv2.IPServiceListResponse); ok {
		r0 = returnFunc(context1, iPServiceListRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv2.IPServiceListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv2.IPServiceListRequest) error); ok {
		r1 = returnFunc(context1, iPServiceListRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IPServiceClient_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type IPServiceClient_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - iPServiceListRequest *apiv2.IPServiceListRequest
func (_e *IPServiceClient_Expecter) List(context1 interface{}, iPServiceListRequest interface{}) *IPServiceClient_List_Call {
	return &IPServiceClient_List_Call{Call: _e.mock.On("List", context1, iPServiceListRequest)}
}

func (_c *IPServiceClient_List_Call) Run(run func(context1 context.Context, iPServiceListRequest *apiv2.IPServiceListRequest)) *IPServiceClient_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv2.IPServiceListRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv2.IPServiceListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IPServiceClient_List_Call) Return(iPServiceListResponse *apiv2.IPServiceListResponse, err error) *IPServiceClient_List_Call {
	_c.Call.Return(iPServiceListResponse, err)
	return _c
}

func (_c *IPServiceClient_List_Call) RunAndReturn(run func(context1 context.Context, iPServiceListRequest *apiv2.IPServiceListRequest) (*apiv2.IPServiceListResponse, error)) *IPServiceClient_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type IPServiceClient
func (_mock *IPServiceClient) Update(context1 context.Context, iPServiceUpdateRequest *apiv2.IPServiceUpdateRequest) (*apiv2.IPServiceUpdateResponse, error) {
	ret := _mock.Called(context1, iPServiceUpdateRequest)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *apiv2.IPServiceUpdateResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv2.IPServiceUpdateRequest) (*apiv2.IPServiceUpdateResponse, error)); ok {
		return returnFunc(context1, iPServiceUpdateRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv2.IPServiceUpdateRequest) *apiv2.IPServiceUpdateResponse); ok {
		r0 = returnFunc(context1, iPServiceUpdateRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv2.IPServiceUpdateResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv2.IPServiceUpdateRequest) error); ok {
		r1 = returnFunc(context1, iPServiceUpdateRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IPServiceClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type IPServiceClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - context1 context.Context
//   - iPServiceUpdateRequest *apiv2.IPServiceUpdateRequest
func (_e *IPServiceClient_Expecter) Update(context1 interface{}, iPServiceUpdateRequest interface{}) *IPServiceClient_Update_Call {
	return &IPServiceClient_Update_Call{Call: _e.mock.On("Update", context1, iPServiceUpdateRequest)}
}

func (_c *IPServiceClient_Update_Call) Run(run func(context1 context.Context, iPServiceUpdateRequest *apiv2.IPServiceUpdateRequest)) *IPServiceClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv2.IPServiceUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv2.IPServiceUpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IPServiceClient_Update_Call) Return(iPServiceUpdateResponse *apiv2.IPServiceUpdateResponse, err error) *IPServiceClient_Update_Call {
	_c.Call.Return(iPServiceUpdateResponse, err)
	return _c
}

func (_c *IPServiceClient_Update_Call) RunAndReturn(run func(context1 context.Context, iPServiceUpdateRequest *apiv2.IPServiceUpdateRequest) (*apiv2.IPServiceUpdateResponse, error)) *IPServiceClient_Update_Call {
	_c.Call.Return(run)
	return _c
}
