// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package apiv2connect

import (
	"context"

	"github.com/metal-stack/api/go/metalstack/api/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewSizeReservationServiceClient creates a new instance of SizeReservationServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSizeReservationServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *SizeReservationServiceClient {
	mock := &SizeReservationServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SizeReservationServiceClient is an autogenerated mock type for the SizeReservationServiceClient type
type SizeReservationServiceClient struct {
	mock.Mock
}

type SizeReservationServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *SizeReservationServiceClient) EXPECT() *SizeReservationServiceClient_Expecter {
	return &SizeReservationServiceClient_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type SizeReservationServiceClient
func (_mock *SizeReservationServiceClient) Get(context1 context.Context, sizeReservationServiceGetRequest *apiv2.SizeReservationServiceGetRequest) (*apiv2.SizeReservationServiceGetResponse, error) {
	ret := _mock.Called(context1, sizeReservationServiceGetRequest)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *apiv2.SizeReservationServiceGetResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv2.SizeReservationServiceGetRequest) (*apiv2.SizeReservationServiceGetResponse, error)); ok {
		return returnFunc(context1, sizeReservationServiceGetRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv2.SizeReservationServiceGetRequest) *apiv2.SizeReservationServiceGetResponse); ok {
		r0 = returnFunc(context1, sizeReservationServiceGetRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv2.SizeReservationServiceGetResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv2.SizeReservationServiceGetRequest) error); ok {
		r1 = returnFunc(context1, sizeReservationServiceGetRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SizeReservationServiceClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type SizeReservationServiceClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - sizeReservationServiceGetRequest *apiv2.SizeReservationServiceGetRequest
func (_e *SizeReservationServiceClient_Expecter) Get(context1 interface{}, sizeReservationServiceGetRequest interface{}) *SizeReservationServiceClient_Get_Call {
	return &SizeReservationServiceClient_Get_Call{Call: _e.mock.On("Get", context1, sizeReservationServiceGetRequest)}
}

func (_c *SizeReservationServiceClient_Get_Call) Run(run func(context1 context.Context, sizeReservationServiceGetRequest *apiv2.SizeReservationServiceGetRequest)) *SizeReservationServiceClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv2.SizeReservationServiceGetRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv2.SizeReservationServiceGetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SizeReservationServiceClient_Get_Call) Return(sizeReservationServiceGetResponse *apiv2.SizeReservationServiceGetResponse, err error) *SizeReservationServiceClient_Get_Call {
	_c.Call.Return(sizeReservationServiceGetResponse, err)
	return _c
}

func (_c *SizeReservationServiceClient_Get_Call) RunAndReturn(run func(context1 context.Context, sizeReservationServiceGetRequest *apiv2.SizeReservationServiceGetRequest) (*apiv2.SizeReservationServiceGetResponse, error)) *SizeReservationServiceClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type SizeReservationServiceClient
func (_mock *SizeReservationServiceClient) List(context1 context.Context, sizeReservationServiceListRequest *apiv2.SizeReservationServiceListRequest) (*apiv2.SizeReservationServiceListResponse, error) {
	ret := _mock.Called(context1, sizeReservationServiceListRequest)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *apiv2.SizeReservationServiceListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv2.SizeReservationServiceListRequest) (*apiv2.SizeReservationServiceListResponse, error)); ok {
		return returnFunc(context1, sizeReservationServiceListRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv2.SizeReservationServiceListRequest) *apiv2.SizeReservationServiceListResponse); ok {
		r0 = returnFunc(context1, sizeReservationServiceListRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv2.SizeReservationServiceListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv2.SizeReservationServiceListRequest) error); ok {
		r1 = returnFunc(context1, sizeReservationServiceListRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SizeReservationServiceClient_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type SizeReservationServiceClient_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - sizeReservationServiceListRequest *apiv2.SizeReservationServiceListRequest
func (_e *SizeReservationServiceClient_Expecter) List(context1 interface{}, sizeReservationServiceListRequest interface{}) *SizeReservationServiceClient_List_Call {
	return &SizeReservationServiceClient_List_Call{Call: _e.mock.On("List", context1, sizeReservationServiceListRequest)}
}

func (_c *SizeReservationServiceClient_List_Call) Run(run func(context1 context.Context, sizeReservationServiceListRequest *apiv2.SizeReservationServiceListRequest)) *SizeReservationServiceClient_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv2.SizeReservationServiceListRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv2.SizeReservationServiceListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SizeReservationServiceClient_List_Call) Return(sizeReservationServiceListResponse *apiv2.SizeReservationServiceListResponse, err error) *SizeReservationServiceClient_List_Call {
	_c.Call.Return(sizeReservationServiceListResponse, err)
	return _c
}

func (_c *SizeReservationServiceClient_List_Call) RunAndReturn(run func(context1 context.Context, sizeReservationServiceListRequest *apiv2.SizeReservationServiceListRequest) (*apiv2.SizeReservationServiceListResponse, error)) *SizeReservationServiceClient_List_Call {
	_c.Call.Return(run)
	return _c
}
