// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file metalstack/api/v2/component.proto (package metalstack.api.v2, syntax proto3)
/* eslint-disable */
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import { file_google_protobuf_duration, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_metalstack_api_v2_common } from "./common_pb";
import { file_metalstack_api_v2_predefined_rules } from "./predefined_rules_pb";
import { file_metalstack_api_v2_token } from "./token_pb";
import { file_metalstack_api_v2_version } from "./version_pb";
/**
 * Describes the file metalstack/api/v2/component.proto.
 */
export const file_metalstack_api_v2_component = /*@__PURE__*/ fileDesc("CiFtZXRhbHN0YWNrL2FwaS92Mi9jb21wb25lbnQucHJvdG8SEW1ldGFsc3RhY2suYXBpLnYyIuICCglDb21wb25lbnQSFgoEdXVpZBgBIAEoCUIIukgFcgOwAQESOAoEdHlwZRgCIAEoDjIgLm1ldGFsc3RhY2suYXBpLnYyLkNvbXBvbmVudFR5cGVCCLpIBYIBAhABEh8KCmlkZW50aWZpZXIYAyABKAlCC7pICHIGwLOusQIBEi4KCnN0YXJ0ZWRfYXQYBCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi8KC3JlcG9ydGVkX2F0GAUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIrCghpbnRlcnZhbBgGIAEoCzIZLmdvb2dsZS5wcm90b2J1Zi5EdXJhdGlvbhIrCgd2ZXJzaW9uGAcgASgLMhoubWV0YWxzdGFjay5hcGkudjIuVmVyc2lvbhInCgV0b2tlbhgIIAEoCzIYLm1ldGFsc3RhY2suYXBpLnYyLlRva2VuIrMBCg5Db21wb25lbnRRdWVyeRIbCgR1dWlkGAEgASgJQgi6SAVyA7ABAUgAiAEBEj0KBHR5cGUYAiABKA4yIC5tZXRhbHN0YWNrLmFwaS52Mi5Db21wb25lbnRUeXBlQgi6SAWCAQIQAUgBiAEBEiQKCmlkZW50aWZpZXIYAyABKAlCC7pICHIGwLOusQIBSAKIAQFCBwoFX3V1aWRCBwoFX3R5cGVCDQoLX2lkZW50aWZpZXIqjAMKDUNvbXBvbmVudFR5cGUSLwoaQ09NUE9ORU5UX1RZUEVfVU5TUEVDSUZJRUQQABoPgrIZC3Vuc3BlY2lmaWVkEisKGENPTVBPTkVOVF9UWVBFX1BJWElFQ09SRRABGg2CshkJcGl4aWVjb3JlEi0KGUNPTVBPTkVOVF9UWVBFX01FVEFMX0NPUkUQAhoOgrIZCm1ldGFsLWNvcmUSKwoYQ09NUE9ORU5UX1RZUEVfTUVUQUxfQk1DEAMaDYKyGQltZXRhbC1ibWMSRQolQ09NUE9ORU5UX1RZUEVfTUVUQUxfSU1BR0VfQ0FDSEVfU1lOQxAEGhqCshkWbWV0YWwtaW1hZ2UtY2FjaGUtc3luYxIzChxDT01QT05FTlRfVFlQRV9NRVRBTF9DT05TT0xFEAUaEYKyGQ1tZXRhbC1jb25zb2xlEkUKJUNPTVBPTkVOVF9UWVBFX01FVEFMX01FVFJJQ1NfRVhQT1JURVIQBhoagrIZFm1ldGFsLW1ldHJpY3MtZXhwb3J0ZXJCxAEKFWNvbS5tZXRhbHN0YWNrLmFwaS52MkIOQ29tcG9uZW50UHJvdG9QAVo1Z2l0aHViLmNvbS9tZXRhbC1zdGFjay9hcGkvZ28vbWV0YWxzdGFjay9hcGkvdjI7YXBpdjKiAgNNQViqAhFNZXRhbHN0YWNrLkFwaS5WMsoCEU1ldGFsc3RhY2tcQXBpXFYy4gIdTWV0YWxzdGFja1xBcGlcVjJcR1BCTWV0YWRhdGHqAhNNZXRhbHN0YWNrOjpBcGk6OlYyYgZwcm90bzM", [file_buf_validate_validate, file_google_protobuf_duration, file_google_protobuf_timestamp, file_metalstack_api_v2_common, file_metalstack_api_v2_predefined_rules, file_metalstack_api_v2_token, file_metalstack_api_v2_version]);
/**
 * Describes the message metalstack.api.v2.Component.
 * Use `create(ComponentSchema)` to create a new message.
 */
export const ComponentSchema = /*@__PURE__*/ messageDesc(file_metalstack_api_v2_component, 0);
/**
 * Describes the message metalstack.api.v2.ComponentQuery.
 * Use `create(ComponentQuerySchema)` to create a new message.
 */
export const ComponentQuerySchema = /*@__PURE__*/ messageDesc(file_metalstack_api_v2_component, 1);
/**
 * ComponentType defines which service is actually pinging
 *
 * @generated from enum metalstack.api.v2.ComponentType
 */
export var ComponentType;
(function (ComponentType) {
    /**
     * COMPONENT_TYPE_UNSPECIFIED is unspecified
     *
     * @generated from enum value: COMPONENT_TYPE_UNSPECIFIED = 0;
     */
    ComponentType[ComponentType["UNSPECIFIED"] = 0] = "UNSPECIFIED";
    /**
     * COMPONENT_TYPE_PIXIECORE is pixiecore
     *
     * @generated from enum value: COMPONENT_TYPE_PIXIECORE = 1;
     */
    ComponentType[ComponentType["PIXIECORE"] = 1] = "PIXIECORE";
    /**
     * COMPONENT_TYPE_METAL_CORE is metal-core
     *
     * @generated from enum value: COMPONENT_TYPE_METAL_CORE = 2;
     */
    ComponentType[ComponentType["METAL_CORE"] = 2] = "METAL_CORE";
    /**
     * COMPONENT_TYPE_METAL_BMC is metal-bmc
     *
     * @generated from enum value: COMPONENT_TYPE_METAL_BMC = 3;
     */
    ComponentType[ComponentType["METAL_BMC"] = 3] = "METAL_BMC";
    /**
     * COMPONENT_TYPE_METAL_IMAGE_CACHE_SYNC is metal-image-cache-sync
     *
     * @generated from enum value: COMPONENT_TYPE_METAL_IMAGE_CACHE_SYNC = 4;
     */
    ComponentType[ComponentType["METAL_IMAGE_CACHE_SYNC"] = 4] = "METAL_IMAGE_CACHE_SYNC";
    /**
     * COMPONENT_TYPE_METAL_CONSOLE is metal-console
     *
     * @generated from enum value: COMPONENT_TYPE_METAL_CONSOLE = 5;
     */
    ComponentType[ComponentType["METAL_CONSOLE"] = 5] = "METAL_CONSOLE";
    /**
     * COMPONENT_TYPE_METAL_METRICS_EXPORTER is metal-metrics-exporter
     *
     * @generated from enum value: COMPONENT_TYPE_METAL_METRICS_EXPORTER = 6;
     */
    ComponentType[ComponentType["METAL_METRICS_EXPORTER"] = 6] = "METAL_METRICS_EXPORTER";
})(ComponentType || (ComponentType = {}));
/**
 * Describes the enum metalstack.api.v2.ComponentType.
 */
export const ComponentTypeSchema = /*@__PURE__*/ enumDesc(file_metalstack_api_v2_component, 0);
