// @generated by protoc-gen-es v2.10.1 with parameter "target=ts"
// @generated from file metalstack/api/v2/version.proto (package metalstack.api.v2, syntax proto3)
/* eslint-disable */
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_metalstack_api_v2_common } from "./common_pb";
/**
 * Describes the file metalstack/api/v2/version.proto.
 */
export const file_metalstack_api_v2_version = /*@__PURE__*/ fileDesc("Ch9tZXRhbHN0YWNrL2FwaS92Mi92ZXJzaW9uLnByb3RvEhFtZXRhbHN0YWNrLmFwaS52MiJSCgdWZXJzaW9uEg8KB3ZlcnNpb24YASABKAkSEAoIcmV2aXNpb24YAiABKAkSEAoIZ2l0X3NoYTEYAyABKAkSEgoKYnVpbGRfZGF0ZRgEIAEoCSIaChhWZXJzaW9uU2VydmljZUdldFJlcXVlc3QiSAoZVmVyc2lvblNlcnZpY2VHZXRSZXNwb25zZRIrCgd2ZXJzaW9uGAEgASgLMhoubWV0YWxzdGFjay5hcGkudjIuVmVyc2lvbjJ8Cg5WZXJzaW9uU2VydmljZRJqCgNHZXQSKy5tZXRhbHN0YWNrLmFwaS52Mi5WZXJzaW9uU2VydmljZUdldFJlcXVlc3QaLC5tZXRhbHN0YWNrLmFwaS52Mi5WZXJzaW9uU2VydmljZUdldFJlc3BvbnNlIgjY8xgB4PMYAkLCAQoVY29tLm1ldGFsc3RhY2suYXBpLnYyQgxWZXJzaW9uUHJvdG9QAVo1Z2l0aHViLmNvbS9tZXRhbC1zdGFjay9hcGkvZ28vbWV0YWxzdGFjay9hcGkvdjI7YXBpdjKiAgNNQViqAhFNZXRhbHN0YWNrLkFwaS5WMsoCEU1ldGFsc3RhY2tcQXBpXFYy4gIdTWV0YWxzdGFja1xBcGlcVjJcR1BCTWV0YWRhdGHqAhNNZXRhbHN0YWNrOjpBcGk6OlYyYgZwcm90bzM", [file_metalstack_api_v2_common]);
/**
 * Describes the message metalstack.api.v2.Version.
 * Use `create(VersionSchema)` to create a new message.
 */
export const VersionSchema = /*@__PURE__*/ messageDesc(file_metalstack_api_v2_version, 0);
/**
 * Describes the message metalstack.api.v2.VersionServiceGetRequest.
 * Use `create(VersionServiceGetRequestSchema)` to create a new message.
 */
export const VersionServiceGetRequestSchema = /*@__PURE__*/ messageDesc(file_metalstack_api_v2_version, 1);
/**
 * Describes the message metalstack.api.v2.VersionServiceGetResponse.
 * Use `create(VersionServiceGetResponseSchema)` to create a new message.
 */
export const VersionServiceGetResponseSchema = /*@__PURE__*/ messageDesc(file_metalstack_api_v2_version, 2);
/**
 * VersionService serves version related functions
 *
 * @generated from service metalstack.api.v2.VersionService
 */
export const VersionService = /*@__PURE__*/ serviceDesc(file_metalstack_api_v2_version, 0);
