// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: metalstack/infra/v2/switch.proto

package infrav2connect

import (
	connect "connectrpc.com/connect/v2"
	context "context"
	v2 "github.com/metal-stack/api/go/metalstack/infra/v2"
	sync "sync"
)

const (
	// SwitchServiceName is the fully-qualified name of the SwitchService service.
	SwitchServiceName = "metalstack.infra.v2.SwitchService"
)

// These constants are the procedure names of the RPCs defined in this package. They're exposed at
// runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SwitchServiceGetProcedure is the procedure name of the SwitchService's Get RPC.
	SwitchServiceGetProcedure = "/metalstack.infra.v2.SwitchService/Get"
	// SwitchServiceRegisterProcedure is the procedure name of the SwitchService's Register RPC.
	SwitchServiceRegisterProcedure = "/metalstack.infra.v2.SwitchService/Register"
	// SwitchServiceHeartbeatProcedure is the procedure name of the SwitchService's Heartbeat RPC.
	SwitchServiceHeartbeatProcedure = "/metalstack.infra.v2.SwitchService/Heartbeat"
)

var (
	switchServiceGetSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v2.File_metalstack_infra_v2_switch_proto.Services().ByName("SwitchService").Methods().ByName("Get"),
			Procedure:  SwitchServiceGetProcedure,
		}
	})
	switchServiceRegisterSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v2.File_metalstack_infra_v2_switch_proto.Services().ByName("SwitchService").Methods().ByName("Register"),
			Procedure:  SwitchServiceRegisterProcedure,
		}
	})
	switchServiceHeartbeatSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v2.File_metalstack_infra_v2_switch_proto.Services().ByName("SwitchService").Methods().ByName("Heartbeat"),
			Procedure:  SwitchServiceHeartbeatProcedure,
		}
	})
)

// SwitchServiceClient is a client for the metalstack.infra.v2.SwitchService service.
type SwitchServiceClient interface {
	// Returns the switch with the specified ID.
	Get(context.Context, *v2.SwitchServiceGetRequest) (*v2.SwitchServiceGetResponse, error)
	// Registers a switch.
	Register(context.Context, *v2.SwitchServiceRegisterRequest) (*v2.SwitchServiceRegisterResponse, error)
	// Heartbeat sends a heartbeat from a switch.
	Heartbeat(context.Context, *v2.SwitchServiceHeartbeatRequest) (*v2.SwitchServiceHeartbeatResponse, error)
}

// NewSwitchServiceClient constructs a client for the metalstack.infra.v2.SwitchService service.
// Multiple service clients may share a single connect.Client.
func NewSwitchServiceClient(client *connect.Client) SwitchServiceClient {
	return &switchServiceClient{client: client}
}

// SwitchServiceHandler is an implementation of the metalstack.infra.v2.SwitchService service.
type SwitchServiceHandler interface {
	// Returns the switch with the specified ID.
	Get(context.Context, *v2.SwitchServiceGetRequest) (*v2.SwitchServiceGetResponse, error)
	// Registers a switch.
	Register(context.Context, *v2.SwitchServiceRegisterRequest) (*v2.SwitchServiceRegisterResponse, error)
	// Heartbeat sends a heartbeat from a switch.
	Heartbeat(context.Context, *v2.SwitchServiceHeartbeatRequest) (*v2.SwitchServiceHeartbeatResponse, error)
}

// RegisterSwitchServiceHandler registers svc as the metalstack.infra.v2.SwitchService
// implementation on server.
func RegisterSwitchServiceHandler(server *connect.Server, svc SwitchServiceHandler) {
	adapter := switchServiceHandler{svc: svc}
	server.Register(
		connect.Method{Spec: switchServiceGetSpec(), Handler: adapter.get},
		connect.Method{Spec: switchServiceRegisterSpec(), Handler: adapter.register},
		connect.Method{Spec: switchServiceHeartbeatSpec(), Handler: adapter.heartbeat},
	)
}

// UnimplementedSwitchServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSwitchServiceHandler struct{}

func (UnimplementedSwitchServiceHandler) Get(context.Context, *v2.SwitchServiceGetRequest) (*v2.SwitchServiceGetResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "metalstack.infra.v2.SwitchService.Get is not implemented")
}

func (UnimplementedSwitchServiceHandler) Register(context.Context, *v2.SwitchServiceRegisterRequest) (*v2.SwitchServiceRegisterResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "metalstack.infra.v2.SwitchService.Register is not implemented")
}

func (UnimplementedSwitchServiceHandler) Heartbeat(context.Context, *v2.SwitchServiceHeartbeatRequest) (*v2.SwitchServiceHeartbeatResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "metalstack.infra.v2.SwitchService.Heartbeat is not implemented")
}

type switchServiceClient struct {
	client *connect.Client
}

func (c *switchServiceClient) Get(ctx context.Context, req *v2.SwitchServiceGetRequest) (*v2.SwitchServiceGetResponse, error) {
	var res v2.SwitchServiceGetResponse
	if err := c.client.CallUnary(ctx, switchServiceGetSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *switchServiceClient) Register(ctx context.Context, req *v2.SwitchServiceRegisterRequest) (*v2.SwitchServiceRegisterResponse, error) {
	var res v2.SwitchServiceRegisterResponse
	if err := c.client.CallUnary(ctx, switchServiceRegisterSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *switchServiceClient) Heartbeat(ctx context.Context, req *v2.SwitchServiceHeartbeatRequest) (*v2.SwitchServiceHeartbeatResponse, error) {
	var res v2.SwitchServiceHeartbeatResponse
	if err := c.client.CallUnary(ctx, switchServiceHeartbeatSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

type switchServiceHandler struct{ svc SwitchServiceHandler }

func (h switchServiceHandler) get(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v2.SwitchServiceGetRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.Get(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h switchServiceHandler) register(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v2.SwitchServiceRegisterRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.Register(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h switchServiceHandler) heartbeat(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v2.SwitchServiceHeartbeatRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.Heartbeat(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}
