// Code generated discover.go. DO NOT EDIT.
package permissions

func GetServices() []string {
	return []string{
		"metalstack.admin.v2.PartitionService",
		"metalstack.admin.v2.TenantService",
		"metalstack.admin.v2.TokenService",
		"metalstack.api.v2.HealthService",
		"metalstack.api.v2.IPService",
		"metalstack.api.v2.MethodService",
		"metalstack.api.v2.PartitionService",
		"metalstack.api.v2.ProjectService",
		"metalstack.api.v2.TenantService",
		"metalstack.api.v2.TokenService",
		"metalstack.api.v2.UserService",
		"metalstack.api.v2.VersionService",
	}
}

func GetServicePermissions() *ServicePermissions {
	return &ServicePermissions{
		Roles: Roles{
			Admin: Admin{
				"ADMIN_ROLE_EDITOR": []string{
					"/metalstack.admin.v2.PartitionService/Create",
					"/metalstack.admin.v2.PartitionService/Update",
					"/metalstack.admin.v2.PartitionService/Delete",
					"/metalstack.admin.v2.PartitionService/Capacity",
					"/metalstack.admin.v2.TenantService/List",
					"/metalstack.admin.v2.TokenService/List",
					"/metalstack.admin.v2.TokenService/Revoke",
				},
				"ADMIN_ROLE_VIEWER": []string{
					"/metalstack.admin.v2.PartitionService/Capacity",
					"/metalstack.admin.v2.TenantService/List",
					"/metalstack.admin.v2.TokenService/List",
				},
			},
			Tenant: Tenant{
				"TENANT_ROLE_EDITOR": []string{
					"/metalstack.api.v2.ProjectService/Create",
					"/metalstack.api.v2.TenantService/Get",
					"/metalstack.api.v2.TenantService/Update",
					"/metalstack.api.v2.TenantService/Delete",
				},
				"TENANT_ROLE_GUEST": []string{
					"/metalstack.api.v2.TenantService/Get",
				},
				"TENANT_ROLE_OWNER": []string{
					"/metalstack.api.v2.ProjectService/Create",
					"/metalstack.api.v2.TenantService/Get",
					"/metalstack.api.v2.TenantService/Update",
					"/metalstack.api.v2.TenantService/Delete",
					"/metalstack.api.v2.TenantService/RemoveMember",
					"/metalstack.api.v2.TenantService/UpdateMember",
					"/metalstack.api.v2.TenantService/Invite",
					"/metalstack.api.v2.TenantService/InviteDelete",
					"/metalstack.api.v2.TenantService/InvitesList",
				},
				"TENANT_ROLE_VIEWER": []string{
					"/metalstack.api.v2.TenantService/Get",
				},
			},
			Project: Project{
				"PROJECT_ROLE_EDITOR": []string{
					"/metalstack.api.v2.IPService/Get",
					"/metalstack.api.v2.IPService/Create",
					"/metalstack.api.v2.IPService/Update",
					"/metalstack.api.v2.IPService/List",
					"/metalstack.api.v2.IPService/Delete",
					"/metalstack.api.v2.ProjectService/Get",
					"/metalstack.api.v2.ProjectService/Update",
				},
				"PROJECT_ROLE_OWNER": []string{
					"/metalstack.api.v2.IPService/Get",
					"/metalstack.api.v2.IPService/Create",
					"/metalstack.api.v2.IPService/Update",
					"/metalstack.api.v2.IPService/List",
					"/metalstack.api.v2.IPService/Delete",
					"/metalstack.api.v2.ProjectService/Get",
					"/metalstack.api.v2.ProjectService/Delete",
					"/metalstack.api.v2.ProjectService/Update",
					"/metalstack.api.v2.ProjectService/RemoveMember",
					"/metalstack.api.v2.ProjectService/UpdateMember",
					"/metalstack.api.v2.ProjectService/Invite",
					"/metalstack.api.v2.ProjectService/InviteDelete",
					"/metalstack.api.v2.ProjectService/InvitesList",
				},
				"PROJECT_ROLE_VIEWER": []string{
					"/metalstack.api.v2.IPService/Get",
					"/metalstack.api.v2.IPService/List",
					"/metalstack.api.v2.ProjectService/Get",
				},
			},
		},
		Methods: map[string]bool{
			"/metalstack.admin.v2.PartitionService/Capacity":   true,
			"/metalstack.admin.v2.PartitionService/Create":     true,
			"/metalstack.admin.v2.PartitionService/Delete":     true,
			"/metalstack.admin.v2.PartitionService/Update":     true,
			"/metalstack.admin.v2.TenantService/List":          true,
			"/metalstack.admin.v2.TokenService/List":           true,
			"/metalstack.admin.v2.TokenService/Revoke":         true,
			"/metalstack.api.v2.HealthService/Get":             true,
			"/metalstack.api.v2.IPService/Create":              true,
			"/metalstack.api.v2.IPService/Delete":              true,
			"/metalstack.api.v2.IPService/Get":                 true,
			"/metalstack.api.v2.IPService/List":                true,
			"/metalstack.api.v2.IPService/Update":              true,
			"/metalstack.api.v2.MethodService/List":            true,
			"/metalstack.api.v2.MethodService/TokenScopedList": true,
			"/metalstack.api.v2.PartitionService/Get":          true,
			"/metalstack.api.v2.PartitionService/List":         true,
			"/metalstack.api.v2.ProjectService/Create":         true,
			"/metalstack.api.v2.ProjectService/Delete":         true,
			"/metalstack.api.v2.ProjectService/Get":            true,
			"/metalstack.api.v2.ProjectService/Invite":         true,
			"/metalstack.api.v2.ProjectService/InviteAccept":   true,
			"/metalstack.api.v2.ProjectService/InviteDelete":   true,
			"/metalstack.api.v2.ProjectService/InviteGet":      true,
			"/metalstack.api.v2.ProjectService/InvitesList":    true,
			"/metalstack.api.v2.ProjectService/List":           true,
			"/metalstack.api.v2.ProjectService/RemoveMember":   true,
			"/metalstack.api.v2.ProjectService/Update":         true,
			"/metalstack.api.v2.ProjectService/UpdateMember":   true,
			"/metalstack.api.v2.TenantService/Create":          true,
			"/metalstack.api.v2.TenantService/Delete":          true,
			"/metalstack.api.v2.TenantService/Get":             true,
			"/metalstack.api.v2.TenantService/Invite":          true,
			"/metalstack.api.v2.TenantService/InviteAccept":    true,
			"/metalstack.api.v2.TenantService/InviteDelete":    true,
			"/metalstack.api.v2.TenantService/InviteGet":       true,
			"/metalstack.api.v2.TenantService/InvitesList":     true,
			"/metalstack.api.v2.TenantService/List":            true,
			"/metalstack.api.v2.TenantService/RemoveMember":    true,
			"/metalstack.api.v2.TenantService/Update":          true,
			"/metalstack.api.v2.TenantService/UpdateMember":    true,
			"/metalstack.api.v2.TokenService/Create":           true,
			"/metalstack.api.v2.TokenService/Get":              true,
			"/metalstack.api.v2.TokenService/List":             true,
			"/metalstack.api.v2.TokenService/Revoke":           true,
			"/metalstack.api.v2.TokenService/Update":           true,
			"/metalstack.api.v2.UserService/Get":               true,
			"/metalstack.api.v2.VersionService/Get":            true,
		},
		Visibility: Visibility{
			Public: map[string]bool{
				"/grpc.reflection.v1.ServerReflection/ServerReflectionInfo":      true,
				"/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo": true,
				"/metalstack.api.v2.HealthService/Get":                           true,
				"/metalstack.api.v2.MethodService/List":                          true,
				"/metalstack.api.v2.VersionService/Get":                          true,
			},
			Self: map[string]bool{
				"/metalstack.api.v2.MethodService/TokenScopedList": true,
				"/metalstack.api.v2.PartitionService/Get":          true,
				"/metalstack.api.v2.PartitionService/List":         true,
				"/metalstack.api.v2.ProjectService/InviteAccept":   true,
				"/metalstack.api.v2.ProjectService/InviteGet":      true,
				"/metalstack.api.v2.ProjectService/List":           true,
				"/metalstack.api.v2.TenantService/Create":          true,
				"/metalstack.api.v2.TenantService/InviteAccept":    true,
				"/metalstack.api.v2.TenantService/InviteGet":       true,
				"/metalstack.api.v2.TenantService/List":            true,
				"/metalstack.api.v2.TokenService/Create":           true,
				"/metalstack.api.v2.TokenService/Get":              true,
				"/metalstack.api.v2.TokenService/List":             true,
				"/metalstack.api.v2.TokenService/Revoke":           true,
				"/metalstack.api.v2.TokenService/Update":           true,
				"/metalstack.api.v2.UserService/Get":               true,
			},
		},
		Auditable: map[string]bool{
			"/metalstack.admin.v2.PartitionService/Capacity":   false,
			"/metalstack.admin.v2.PartitionService/Create":     true,
			"/metalstack.admin.v2.PartitionService/Delete":     true,
			"/metalstack.admin.v2.PartitionService/Update":     true,
			"/metalstack.admin.v2.TenantService/List":          true,
			"/metalstack.admin.v2.TokenService/List":           true,
			"/metalstack.admin.v2.TokenService/Revoke":         true,
			"/metalstack.api.v2.HealthService/Get":             false,
			"/metalstack.api.v2.IPService/Create":              true,
			"/metalstack.api.v2.IPService/Delete":              true,
			"/metalstack.api.v2.IPService/Get":                 false,
			"/metalstack.api.v2.IPService/List":                false,
			"/metalstack.api.v2.IPService/Update":              true,
			"/metalstack.api.v2.MethodService/List":            true,
			"/metalstack.api.v2.MethodService/TokenScopedList": true,
			"/metalstack.api.v2.PartitionService/Get":          false,
			"/metalstack.api.v2.PartitionService/List":         false,
			"/metalstack.api.v2.ProjectService/Create":         true,
			"/metalstack.api.v2.ProjectService/Delete":         true,
			"/metalstack.api.v2.ProjectService/Get":            false,
			"/metalstack.api.v2.ProjectService/Invite":         true,
			"/metalstack.api.v2.ProjectService/InviteAccept":   true,
			"/metalstack.api.v2.ProjectService/InviteDelete":   true,
			"/metalstack.api.v2.ProjectService/InviteGet":      false,
			"/metalstack.api.v2.ProjectService/InvitesList":    false,
			"/metalstack.api.v2.ProjectService/List":           false,
			"/metalstack.api.v2.ProjectService/RemoveMember":   true,
			"/metalstack.api.v2.ProjectService/Update":         true,
			"/metalstack.api.v2.ProjectService/UpdateMember":   true,
			"/metalstack.api.v2.TenantService/Create":          true,
			"/metalstack.api.v2.TenantService/Delete":          true,
			"/metalstack.api.v2.TenantService/Get":             false,
			"/metalstack.api.v2.TenantService/Invite":          true,
			"/metalstack.api.v2.TenantService/InviteAccept":    true,
			"/metalstack.api.v2.TenantService/InviteDelete":    true,
			"/metalstack.api.v2.TenantService/InviteGet":       false,
			"/metalstack.api.v2.TenantService/InvitesList":     false,
			"/metalstack.api.v2.TenantService/List":            false,
			"/metalstack.api.v2.TenantService/RemoveMember":    true,
			"/metalstack.api.v2.TenantService/Update":          true,
			"/metalstack.api.v2.TenantService/UpdateMember":    true,
			"/metalstack.api.v2.TokenService/Create":           true,
			"/metalstack.api.v2.TokenService/Get":              true,
			"/metalstack.api.v2.TokenService/List":             true,
			"/metalstack.api.v2.TokenService/Revoke":           true,
			"/metalstack.api.v2.TokenService/Update":           true,
			"/metalstack.api.v2.UserService/Get":               true,
			"/metalstack.api.v2.VersionService/Get":            false,
		},
	}
}
